/*Config
	Retorno
		-IndiceValoresEntidade
	Parametros
		-DT_REFERENCIA:DateTime
*/

SELECT DISTINCT IV.* 
 FROM TB_IND_VALORES IV 
INNER JOIN TB_EMPRESA_PLANOS EP ON IV.COD_IND = EP.IND_RESERVA_POUP
WHERE EP.CD_FUNDACAO = '01'
  AND EP.CD_PLANO = '0002'
  AND IV.DT_IND = @DT_REFERENCIA