/*Config
    Retorno
        -FichaFechamentoEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -CD_PLANO:string
        -NUM_INSCRICAO:string
*/

SELECT *
FROM CC_FICHA_FECHAMENTO FF
WHERE FF.CD_FUNDACAO = @CD_FUNDACAO
  AND FF.CD_EMPRESA = @CD_EMPRESA
  AND FF.CD_PLANO = @CD_PLANO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.ANO_REF = (SELECT MAX(FF1.ANO_REF)
				    FROM CC_FICHA_FECHAMENTO FF1
				    WHERE FF1.CD_FUNDACAO = FF.CD_FUNDACAO
				    AND FF1.CD_PLANO = FF.CD_PLANO
				    AND FF1.NUM_INSCRICAO = FF.NUM_INSCRICAO)
  AND FF.MES_REF = (SELECT MAX(FF1.MES_REF)
				    FROM CC_FICHA_FECHAMENTO FF1
				    WHERE FF1.CD_FUNDACAO = FF.CD_FUNDACAO
				    AND FF1.CD_PLANO = FF.CD_PLANO
				    AND FF1.NUM_INSCRICAO = FF.NUM_INSCRICAO
                    AND FF1.ANO_REF = FF.ANO_REF)
ORDER BY FF.DT_FECHAMENTO DESC