/*Config
    RetornaLista
    Retorno
        -FichaFechamentoEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -CD_PLANO:string
        -NUM_INSCRICAO:string
        -DT_INICIO:string
        -DT_FIM:string
*/

SELECT FF.*
FROM CC_FICHA_FECHAMENTO FF
INNER JOIN CS_FUNCIONARIO FUNC ON FUNC.NUM_INSCRICAO = FF.NUM_INSCRICAO
WHERE FF.CD_FUNDACAO = @CD_FUNDACAO
  AND FF.CD_EMPRESA = @CD_EMPRESA
  AND FF.CD_PLANO = @CD_PLANO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND ('' + FF.ANO_REF + FF.MES_REF BETWEEN @DT_INICIO AND @DT_FIM)
ORDER BY FF.CD_FUNDACAO,
         FF.CD_EMPRESA,
         FF.NUM_INSCRICAO,
         FF.ANO_REF,
         FF.MES_REF