/*Config
    RetornaLista
    Retorno
        -DocumentoAtualizacaoCadastralEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
*/

SELECT EE.NOME_ENTID, AU.OID_ARQUIVO_UPLOAD, AU.NOM_ARQUIVO_ORIGINAL, AU.NOM_ARQUIVO_LOCAL, AU.DTA_UPLOAD
FROM WEB_DOC_ATU_CADASTRAL DC
INNER JOIN TBG_ARQUIVO_UPLOAD AU ON AU.OID_ARQUIVO_UPLOAD = DC.OID_ARQUIVO_UPLOAD
INNER JOIN CS_FUNCIONARIO FU ON FU.CD_FUNDACAO = DC.CD_FUNDACAO AND FU.NUM_INSCRICAO = DC.NUM_INSCRICAO
INNER JOIN EE_ENTIDADE EE ON EE.COD_ENTID = FU.COD_ENTID
WHERE DC.CD_FUNDACAO = @CD_FUNDACAO
  AND DC.NUM_INSCRICAO = @NUM_INSCRICAO
ORDER BY AU.DTA_UPLOAD DESC