/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraAssistidoEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -NUM_MATRICULA:string
        -CD_PLANO:string
*/

SELECT DISTINCT 
    ANO_PROCESSO,
    NUM_PROCESSO,
    TB_PLANOS.CD_PLANO,
    TB_PLANOS.DS_PLANO,
    DT_REFERENCIA, 
    GB_FICHA_FINANC_ASSISTIDO.CD_TIPO_FOLHA, 
	DS_TIPO_FOLHA,
	GB_ESPECIE_BENEFICIO.CD_ESPECIE,
	GB_ESPECIE_BENEFICIO.DS_ESPECIE
FROM GB_FICHA_FINANC_ASSISTIDO
INNER JOIN GB_RECEBEDOR_BENEFICIO ON GB_FICHA_FINANC_ASSISTIDO.SEQ_RECEBEDOR = GB_RECEBEDOR_BENEFICIO.SEQ_RECEBEDOR
INNER JOIN TB_TIPO_FOLHA TF ON TF.CD_TIPO_FOLHA = GB_FICHA_FINANC_ASSISTIDO.CD_TIPO_FOLHA
INNER JOIN GB_ESPECIE_BENEFICIO ON GB_ESPECIE_BENEFICIO.CD_ESPECIE = GB_FICHA_FINANC_ASSISTIDO.CD_ESPECIE
INNER JOIN TB_PLANOS ON TB_PLANOS.CD_FUNDACAO = GB_FICHA_FINANC_ASSISTIDO.CD_FUNDACAO AND TB_PLANOS.CD_PLANO = GB_FICHA_FINANC_ASSISTIDO.CD_PLANO
WHERE GB_FICHA_FINANC_ASSISTIDO.CD_FUNDACAO = @CD_FUNDACAO
  AND GB_RECEBEDOR_BENEFICIO.CD_FUNDACAO = @CD_FUNDACAO
  AND GB_FICHA_FINANC_ASSISTIDO.CD_EMPRESA = @CD_EMPRESA
  AND GB_RECEBEDOR_BENEFICIO.CD_EMPRESA = @CD_EMPRESA
  AND GB_FICHA_FINANC_ASSISTIDO.CD_PLANO = @CD_PLANO
  AND NUM_MATRICULA = @NUM_MATRICULA
  AND GB_RECEBEDOR_BENEFICIO.CD_TIPO_RECEBEDOR = 'A'
GROUP BY 
    ANO_PROCESSO,
    NUM_PROCESSO,
    TB_PLANOS.CD_PLANO,
    TB_PLANOS.DS_PLANO,
    DT_REFERENCIA, 
    DT_COMPETENCIA, 
    GB_FICHA_FINANC_ASSISTIDO.CD_TIPO_FOLHA, 
    DS_TIPO_FOLHA,
	GB_ESPECIE_BENEFICIO.CD_ESPECIE,
	GB_ESPECIE_BENEFICIO.DS_ESPECIE
ORDER BY DT_REFERENCIA DESC