/*Config
	Retorno
		-FichaFinanceiraAssistidoEntidade
	Parametros
		-CD_FUNDACAO:string
		-CD_EMPRESA:string
		-NUM_MATRICULA:string
*/

SELECT B.NUM_MATRICULA, ISNULL(B.NUM_SEQ_GR_FAMIL,0) AS NUM_SEQ_GR_FAMIL, B.CD_EMPRESA, 
	          A.CD_PLANO, A.DT_REFERENCIA, A.CD_RUBRICA, A.VALOR_MC 
	     FROM GB_FICHA_FINANC_ASSISTIDO A
   INNER JOIN GB_RECEBEDOR_BENEFICIO B 
           ON B.CD_FUNDACAO = A.CD_FUNDACAO
          AND B.CD_EMPRESA = A.CD_EMPRESA
		  AND B.SEQ_RECEBEDOR = A.SEQ_RECEBEDOR
   INNER JOIN EE_ENTIDADE C
           ON C.COD_ENTID = B.COD_ENTID
        WHERE A.CD_FUNDACAO = @CD_FUNDACAO
		  AND A.CD_EMPRESA = @CD_EMPRESA
		  AND B.NUM_MATRICULA = @NUM_MATRICULA
		  AND ISNULL(B.NUM_SEQ_GR_FAMIL,0) = 0
		  AND A.DT_REFERENCIA = (SELECT MAX(B1.DT_REFERENCIA) 
		                           FROM GB_FICHA_FINANC_ASSISTIDO B1
								  WHERE B1.CD_FUNDACAO = A.CD_FUNDACAO
								    AND B1.CD_EMPRESA = A.CD_EMPRESA
									AND B1.CD_PLANO = '0001'
									AND B1.SEQ_RECEBEDOR = B.SEQ_RECEBEDOR
									AND B1.DT_REFERENCIA <= GETDATE())
		  AND A.CD_RUBRICA = '6070'
		  AND A.CD_PLANO = '0001'