/*Config
    RetornaLista
    Retorno
        -HeaderInfoRendEntidade
    Parametros
        -CPF:string
*/

SELECT TB_HEADER_INFO_REND.*,
    EE_ENTIDADE.NOME_ENTID AS NOM_EMPRESA,
    EE_ENTIDADE.CPF_CGC    AS CNPJ_EMPRESA,
	('' + CAST(TB_HEADER_INFO_REND.ANO_EXERCICIO AS VARCHAR(10)) + ' - ' + TB_HEADER_INFO_REND.DESC_NATUREZA) AS ANO_EXERCICIO_DESC_NATUREZA
FROM   TB_HEADER_INFO_REND
INNER JOIN TB_EMPRESA ON TB_HEADER_INFO_REND.CD_EMPRESA = TB_EMPRESA.CD_EMPRESA
INNER JOIN TB_FUNDACAO ON TB_EMPRESA.CD_FUNDACAO = TB_FUNDACAO.CD_FUNDACAO
INNER JOIN EE_ENTIDADE ON TB_FUNDACAO.COD_ENTID = EE_ENTIDADE.COD_ENTID
WHERE TB_HEADER_INFO_REND.CPF = @CPF