/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_PLANO:string
*/

SELECT SUM(CASE WHEN FF.CD_OPERACAO = 'D' THEN FF.CONTRIB_PARTICIPANTE * -1 ELSE FF.CONTRIB_PARTICIPANTE END) AS CONTRIB_PARTICIPANTE,
       SUM(CASE WHEN FF.CD_OPERACAO = 'D' THEN FF.CONTRIB_EMPRESA * -1 ELSE FF.CONTRIB_EMPRESA END) AS CONTRIB_EMPRESA,
       SUM(CASE WHEN FF.CD_OPERACAO = 'D' THEN ISNULL(FF.QTD_COTA_RP_PARTICIPANTE,0) * -1 ELSE ISNULL(FF.QTD_COTA_RP_PARTICIPANTE,0) END) AS QTD_COTA_RP_PARTICIPANTE,
       SUM(CASE WHEN FF.CD_OPERACAO = 'D' THEN ISNULL(FF.QTD_COTA_RP_EMPRESA,0) * -1 ELSE ISNULL(FF.QTD_COTA_RP_EMPRESA,0) END) AS QTD_COTA_RP_EMPRESA
FROM CC_FICHA_FINANCEIRA FF
    INNER JOIN TB_TIPO_CONTRIBUICAO TC ON TC.CD_TIPO_CONTRIBUICAO = FF.CD_TIPO_CONTRIBUICAO
WHERE FF.CD_FUNDACAO   = @CD_FUNDACAO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.CD_PLANO      = @CD_PLANO
  AND TC.COMPOE_SALDO_BENEFICIO = 'S'
  AND TC.RECURSO_PORTADO = 'N'