/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_PLANO:string
        -NUM_INSCRICAO:string
*/

SELECT TB_TIPO_CONTRIBUICAO.DS_TIPO_CONTRIBUICAO,
       TB_TIPO_CONTRIBUICAO.CALC_MARGEM_CONSIG,
       CC_FICHA_FINANCEIRA.* 
FROM CC_FICHA_FINANCEIRA
INNER JOIN TB_TIPO_CONTRIBUICAO ON TB_TIPO_CONTRIBUICAO.CD_TIPO_CONTRIBUICAO = CC_FICHA_FINANCEIRA.CD_TIPO_CONTRIBUICAO
WHERE CC_FICHA_FINANCEIRA.CD_FUNDACAO = @CD_FUNDACAO
  AND CC_FICHA_FINANCEIRA.CD_PLANO = @CD_PLANO
  AND CC_FICHA_FINANCEIRA.NUM_INSCRICAO = @NUM_INSCRICAO
  AND CC_FICHA_FINANCEIRA.SRC > 0
  AND CC_FICHA_FINANCEIRA.ANO_REF = (SELECT MAX(FF1.ANO_REF)
				                     FROM CC_FICHA_FINANCEIRA FF1
				                     WHERE FF1.CD_FUNDACAO = @CD_FUNDACAO
				                       AND FF1.CD_PLANO = @CD_PLANO
									   AND FF1.SRC > 0
				                       AND FF1.NUM_INSCRICAO = @NUM_INSCRICAO)
  AND CC_FICHA_FINANCEIRA.MES_REF = (SELECT MAX(FF1.MES_REF)
				                     FROM CC_FICHA_FINANCEIRA FF1
				                     WHERE FF1.CD_FUNDACAO = @CD_FUNDACAO
				                       AND FF1.CD_PLANO = @CD_PLANO
				                       AND FF1.NUM_INSCRICAO = @NUM_INSCRICAO
									   AND FF1.SRC > 0
                                       AND FF1.ANO_REF = CC_FICHA_FINANCEIRA.ANO_REF)
ORDER BY CC_FICHA_FINANCEIRA.CD_TIPO_CONTRIBUICAO