/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_PLANO:string
        -MES_REF_INI:string
        -ANO_REF_INI:string
        -MES_REF_FIM:string
        -ANO_REF_FIM:string
*/

SELECT FF.ANO_REF,
       FF.MES_REF,
       FF.CD_OPERACAO,
       FF.ANO_COMP,
       FF.MES_COMP,
       TC.DS_TIPO_CONTRIBUICAO,
       FF.SRC,
       FF.CONTRIB_PARTICIPANTE,
       FF.CONTRIB_EMPRESA,
       FF.QTD_COTA_RP_PARTICIPANTE,
       FF.QTD_COTA_RP_EMPRESA,
       0 + FF.QTD_COTA_RP_EMPRESA + FF.QTD_COTA_RP_PARTICIPANTE AS QTD_COTA,
       IV.VALOR_IND
FROM CC_FICHA_FINANCEIRA FF
    INNER JOIN TB_TIPO_CONTRIBUICAO TC ON TC.CD_TIPO_CONTRIBUICAO = FF.CD_TIPO_CONTRIBUICAO
    INNER JOIN CS_FUNCIONARIO FN ON FN.CD_FUNDACAO = FF.CD_FUNDACAO
        AND FN.NUM_INSCRICAO = FF.NUM_INSCRICAO
    INNER JOIN TB_EMPRESA_PLANOS EP ON EP.CD_FUNDACAO= FF.CD_FUNDACAO
        AND EP.CD_EMPRESA = FN.CD_EMPRESA
        AND EP.CD_PLANO = FF.CD_PLANO
    LEFT OUTER JOIN CA_DATA_RECOLHIMENTO DR ON DR.CD_FUNDACAO = FF.CD_FUNDACAO
        AND DR.CD_EMPRESA = FN.CD_EMPRESA
        AND DR.ANO_REF = FF.ANO_REF
        AND DR.MES_REF = FF.MES_REF
        AND DR.SEQ_CONTRIBUICAO = FF.SEQ_CONTRIBUICAO
    LEFT OUTER JOIN TB_IND_VALORES IV ON IV.COD_IND = EP.IND_RESERVA_POUP
        AND IV.DT_IND = DR.DT_REC_RP_PARTICIPANTE
WHERE FF.CD_FUNDACAO   = @CD_FUNDACAO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.CD_PLANO      = @CD_PLANO
  AND FF.ANO_REF * 12 + FF.MES_REF >= @ANO_REF_INI * 12 + @MES_REF_INI
  AND FF.ANO_REF * 12 + FF.MES_REF <= @ANO_REF_FIM * 12 + @MES_REF_FIM
  AND TC.COMPOE_SALDO_BENEFICIO = 'S'
ORDER BY FF.ANO_REF,
       FF.MES_REF,
       FF.ANO_COMP,
       FF.MES_COMP,
       TC.DS_TIPO_CONTRIBUICAO