/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_PLANO:string
		-ANO_REF:string
		-MES_REF:string
		-ANO_INI:string
		-MES_INI:string
*/

SELECT TC.CD_TIPO_CONTRIBUICAO,
       TC.DS_TIPO_CONTRIBUICAO,
       FF.CD_FUNDACAO,
       FF.NUM_INSCRICAO,
       FF.CD_PLANO,
       FF.ANO_REF,
       FF.MES_REF,
       SUM(ISNULL(FF.CONTRIB_PARTICIPANTE,0)) AS CONTRIB_PARTICIPANTE,
       SUM(ISNULL(FF.CONTRIB_EMPRESA,0)) AS CONTRIB_EMPRESA,
       SUM((ISNULL(FF.CONTRIB_PARTICIPANTE,0) + ISNULL(FF.CONTRIB_EMPRESA,0))) AS TOTAL_CONTRIB,
       SUM(ISNULL(FF.QTD_COTA_RP_PARTICIPANTE, 0)) AS QTD_COTA_RP_PARTICIPANTE,
       SUM(ISNULL(FF.QTD_COTA_RP_EMPRESA, 0)) AS QTD_COTA_RP_EMPRESA,
       SUM((ISNULL(FF.QTD_COTA_RP_PARTICIPANTE,0) + ISNULL(FF.QTD_COTA_RP_EMPRESA,0))) AS COTA_TOTAL,
       MAX(IV.VALOR_IND) AS VALOR_IND,
       MAX((ISNULL(IV.VALOR_IND,0) / ISNULL(IVA.VALOR_IND,1) - 1) * 100) AS RENTABILIDADE,
       (SELECT SUM(ISNULL(FF2.QTD_COTA_RP_PARTICIPANTE,0) + ISNULL(FF2.QTD_COTA_RP_EMPRESA,0)) 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COMPOE_SALDO_BENEFICIO = 'S'
           AND FF2.CD_FUNDACAO = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF * 13 + FF2.MES_REF <= FF.ANO_REF * 13 + FF.MES_REF) AS SALDO_COTA,
       (SELECT SUM(ISNULL(FF2.QTD_COTA_RP_PARTICIPANTE,0) + ISNULL(FF2.QTD_COTA_RP_EMPRESA,0)) 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COMPOE_SALDO_BENEFICIO = 'S'
           AND FF2.CD_FUNDACAO = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF * 13 + FF2.MES_REF <= FF.ANO_REF * 13 + FF.MES_REF) * MAX(IV.VALOR_IND) AS SALDO_REAIS           
FROM CC_FICHA_FINANCEIRA FF
    INNER JOIN TB_TIPO_CONTRIBUICAO TC ON TC.CD_TIPO_CONTRIBUICAO = FF.CD_TIPO_CONTRIBUICAO
    INNER JOIN CS_FUNCIONARIO FN ON FN.CD_FUNDACAO = FF.CD_FUNDACAO
       AND FN.NUM_INSCRICAO = FF.NUM_INSCRICAO
    INNER JOIN TB_EMPRESA_PLANOS EP ON EP.CD_FUNDACAO = FF.CD_FUNDACAO
       AND EP.CD_EMPRESA = FN.CD_EMPRESA
       AND EP.CD_PLANO   = FF.CD_PLANO
    LEFT OUTER JOIN TB_IND_VALORES IV ON IV.COD_IND = EP.IND_RESERVA_POUP
    LEFT OUTER JOIN TB_IND_VALORES IVA ON IVA.COD_IND = EP.IND_RESERVA_POUP
WHERE FF.CD_FUNDACAO   = @CD_FUNDACAO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.CD_PLANO      = @CD_PLANO
  AND FF.ANO_REF * 13 + FF.MES_REF >= @ANO_INI * 13 + @MES_INI 
  AND FF.ANO_REF * 13 + FF.MES_REF <= @ANO_REF * 13 + @MES_REF 
  
  AND IV.DT_IND = (SELECT MAX(IV2.DT_IND)
                     FROM TB_IND_VALORES IV2
                    WHERE IV2.COD_IND = IV.COD_IND
                      AND CAST(MONTH(IV2.DT_IND) AS INT) = CAST(FF.MES_REF AS INT)
                      AND CAST(YEAR(IV2.DT_IND) AS INT)  = CAST(FF.ANO_REF AS INT))                                
  AND IVA.DT_IND = (SELECT MAX(IV3.DT_IND)
                     FROM TB_IND_VALORES IV3
                    WHERE IV3.COD_IND = IVA.COD_IND
                      AND MONTH(IV3.DT_IND) = MONTH(DATEADD(MONTH, -1, DATEFROMPARTS(CAST(FF.ANO_REF AS INT) , CAST(FF.MES_REF AS INT), 1 )))
                      AND YEAR(IV3.DT_IND)  = YEAR(DATEADD(MONTH, -1, DATEFROMPARTS(CAST(FF.ANO_REF AS INT) , CAST(FF.MES_REF AS INT), 1 ))))  
GROUP BY FF.CD_FUNDACAO,
         FF.NUM_INSCRICAO,
         FF.CD_PLANO,
         FF.ANO_REF,
         FF.MES_REF,
		 TC.DS_TIPO_CONTRIBUICAO,
		 TC.CD_TIPO_CONTRIBUICAO
ORDER BY FF.ANO_REF DESC,
         FF.MES_REF DESC