/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_PLANO:string
        -NUM_INSCRICAO:string
        -ANO_REF:string
*/

SELECT FF.CD_TIPO_CONTRIBUICAO,
       TC.DS_TIPO_CONTRIBUICAO,
       FF.*
FROM CC_FICHA_FINANCEIRA FF
  INNER JOIN TB_TIPO_CONTRIBUICAO TC ON TC.CD_TIPO_CONTRIBUICAO = FF.CD_TIPO_CONTRIBUICAO
  INNER JOIN CS_FUNCIONARIO FN ON FN.CD_FUNDACAO = FF.CD_FUNDACAO AND FN.NUM_INSCRICAO = FF.NUM_INSCRICAO
WHERE FF.CD_FUNDACAO = @CD_FUNDACAO
  AND FF.CD_PLANO = @CD_PLANO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.ANO_REF = @ANO_REF
  AND FF.CD_TIPO_CONTRIBUICAO IN ('73','70','74','34','B4','B6','B5','B1','B2','B3','B7','B8','B9','C1','C5','C6','D5')
ORDER BY ANO_REF DESC, MES_REF DESC