/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_PLANO:string
		-ANO_REF:string
		-MES_REF:string
		-ANO_INI:string
		-MES_INI:string
*/

SELECT FF.ANO_REF,
       FF.MES_REF,
       TC.DS_TIPO_CONTRIBUICAO,
       FF.CONTRIB_PARTICIPANTE,
       FF.CONTRIB_EMPRESA,
       (0 + ISNULL(FF.CONTRIB_PARTICIPANTE,0) + ISNULL(FF.CONTRIB_EMPRESA,0)) AS TOTAL_CONTRIB,
       FF.QTD_COTA_RP_PARTICIPANTE,       
       FF.QTD_COTA_RP_EMPRESA,
       (0 + ISNULL(FF.QTD_COTA_RP_PARTICIPANTE,0) + ISNULL(FF.QTD_COTA_RP_EMPRESA,0)) AS QTD_COTA
FROM CC_FICHA_FINANCEIRA FF
    INNER JOIN TB_TIPO_CONTRIBUICAO TC ON TC.CD_TIPO_CONTRIBUICAO = FF.CD_TIPO_CONTRIBUICAO
WHERE FF.CD_FUNDACAO = @CD_FUNDACAO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND CD_PLANO = @CD_PLANO
  AND FF.ANO_REF * 13 + FF.MES_REF >= @ANO_INI * 13 + @MES_INI
  AND FF.ANO_REF * 13 + FF.MES_REF <= @ANO_REF * 13 + @MES_REF
  AND TC.COMPOE_SALDO_BENEFICIO = 'S'
ORDER BY FF.ANO_REF,
         FF.MES_REF,
         TC.DS_TIPO_CONTRIBUICAO