/*Config
    RetornaLista
    Retorno
        -dynamic
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_PLANO:string
		-ANO_REF:string
		-MES_REF:string
		-ANO_INI:string
		-MES_INI:string
*/

SELECT FF.CD_FUNDACAO,
       FF.NUM_INSCRICAO,
       FF.CD_PLANO,
       FF.ANO_REF,
       FF.MES_REF,
       /* contribuição básica participante em reais */
       ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_PARTICIPANTE * -1 ELSE FF2.CONTRIB_PARTICIPANTE END,0)) AS CONTRIB_PARTICIPANTE 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'BAS'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS CONTRIB_PARTICIPANTE,
       /* contribuição básica participante em cotas */
       ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0)) AS QTD_COTA_RP_PARTICIPANTE
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'BAS'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS QTD_COTA_RP_PARTICIPANTE,
        /* contribuição básica patrocinadora em reais */
          ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_EMPRESA * -1 ELSE FF2.CONTRIB_EMPRESA END,0)) AS  CONTRIB_EMPRESA
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'BAS'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS CONTRIB_EMPRESA,     
       /* contribuição básica patrocinadora em cotas */
          ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_EMPRESA * -1 ELSE FF2.QTD_COTA_RP_EMPRESA END,0)) AS  QTD_COTA_RP_EMPRESA
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'BAS'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS QTD_COTA_RP_EMPRESA,
        /* contribuição risco participante */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_PARTICIPANTE * -1 ELSE FF2.CONTRIB_PARTICIPANTE END,0)) AS RISCO_PART 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'RIS'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS RISCO_PART,
        /* contribuição risco patrocinadora */
          ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_EMPRESA * -1 ELSE FF2.CONTRIB_EMPRESA END,0)) AS  RISCO_PATROC
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'RIS'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS RISCO_PATROC,
        /* contribuição administrativa participante */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_PARTICIPANTE * -1 ELSE FF2.CONTRIB_PARTICIPANTE END,0)) AS ADM_PART 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'ADM'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS ADM_PART,
        /* contribuição administrativa patrocinadora */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_EMPRESA * -1 ELSE FF2.CONTRIB_EMPRESA END,0)) AS  ADM_PATROC
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'ADM'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS ADM_PATROC,
        /* contribuição voluntária participante em reais */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_PARTICIPANTE * -1 ELSE FF2.CONTRIB_PARTICIPANTE END,0)) AS VOLUNTARIA_PART 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'VOL'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS VOLUNTARIA_PART,
        /* contribuição voluntária participante em cotas */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0)) AS VOLUNTARIA_PART_COTA 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'VOL'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS VOLUNTARIA_PART_COTA,
        /* contribuição portabilidade participante em reais */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_PARTICIPANTE * -1 ELSE FF2.CONTRIB_PARTICIPANTE END,0)) AS PORTABILIDADE 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'POR'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS PORTABILIDADE,       
        /* contribuição portabilidade participante em cotas */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0)) AS PORTABILIDADE_COTA 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB = 'POR'
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS PORTABILIDADE_COTA,
        /* total de contribuições que compõem benefício, em reais */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_PARTICIPANTE * -1 ELSE FF2.CONTRIB_PARTICIPANTE END,0) + 
             ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_EMPRESA * -1 ELSE FF2.CONTRIB_EMPRESA END,0)) AS TOTAL_CONTRIB
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB IN ('BAS', 'VOL', 'POR')
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS TOTAL_CONTRIB,
        /* total de contribuições que compõem benefício, em cotas */
        ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0) + 
             ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_EMPRESA * -1 ELSE FF2.QTD_COTA_RP_EMPRESA  END,0)) AS TOTAL_CONTRIB
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB IN ('BAS', 'VOL', 'POR')
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0) AS TOTAL_CONTRIB_COTAS,
       /* valor da cota do mês */
       MAX(IV.VALOR_IND) AS VALOR_IND,
       /* rentabilidade percentual */
       MAX((ISNULL(IV.VALOR_IND,0) / ISNULL(IVA.VALOR_IND,1) - 1) * 100) AS RENTABILIDADE,
       /* saldo do mês em cotas */
       (SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0) + 
            ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_EMPRESA * -1 ELSE FF2.QTD_COTA_RP_EMPRESA  END,0)) 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB IN ('BAS', 'VOL', 'POR')
           AND FF2.CD_FUNDACAO = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF * 13 + FF2.MES_REF <= FF.ANO_REF * 13 + FF.MES_REF) AS SALDO_COTA,
       /* saldo do mês em reais */
       (SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0) + 
            ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_EMPRESA * -1 ELSE FF2.QTD_COTA_RP_EMPRESA  END,0)) 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB IN ('BAS', 'VOL', 'POR')
           AND FF2.CD_FUNDACAO = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF * 13 + FF2.MES_REF <= FF.ANO_REF * 13 + FF.MES_REF) * MAX(IV.VALOR_IND) AS SALDO_REAIS,           
       /* Rendimento do mes em reais (Saldo_reais_mes - Saldo_Reais_Mes_anterior - Contrib_total_mes) */
       ((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0) + 
            ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_EMPRESA * -1 ELSE FF2.QTD_COTA_RP_EMPRESA  END,0)) 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB IN ('BAS', 'VOL', 'POR')
           AND FF2.CD_FUNDACAO = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF * 13 + FF2.MES_REF <= FF.ANO_REF * 13 + FF.MES_REF) * MAX(IV.VALOR_IND)) -
        (ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF2.QTD_COTA_RP_PARTICIPANTE END,0) + 
            ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.QTD_COTA_RP_EMPRESA * -1 ELSE FF2.QTD_COTA_RP_EMPRESA  END,0)) 
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB IN ('BAS', 'VOL', 'POR')
           AND FF2.CD_FUNDACAO = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF * 13 + FF2.MES_REF < FF.ANO_REF * 13 + FF.MES_REF) * MAX(IVA.VALOR_IND),0)) - 
        (ISNULL((SELECT SUM(ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_PARTICIPANTE * -1 ELSE FF2.CONTRIB_PARTICIPANTE END,0) + 
             ISNULL(CASE WHEN FF2.CD_OPERACAO = 'D' THEN FF2.CONTRIB_EMPRESA * -1 ELSE FF2.CONTRIB_EMPRESA END,0)) AS TOTAL_CONTRIB
          FROM CC_FICHA_FINANCEIRA FF2 
               INNER JOIN TB_TIPO_CONTRIBUICAO TC2 ON TC2.CD_TIPO_CONTRIBUICAO = FF2.CD_TIPO_CONTRIBUICAO
         WHERE TC2.COD_AGRUPADOR_WEB IN ('BAS', 'VOL', 'POR')
           AND FF2.CD_FUNDACAO   = FF.CD_FUNDACAO
           AND FF2.NUM_INSCRICAO = FF.NUM_INSCRICAO
           AND FF2.CD_PLANO      = FF.CD_PLANO
           AND FF2.ANO_REF       = FF.ANO_REF
           AND FF2.MES_REF       = FF.MES_REF),0)) AS RENDIMENTO_MES
FROM CC_FICHA_FINANCEIRA FF
    INNER JOIN TB_TIPO_CONTRIBUICAO TC ON TC.CD_TIPO_CONTRIBUICAO = FF.CD_TIPO_CONTRIBUICAO
    INNER JOIN CS_FUNCIONARIO FN ON FN.CD_FUNDACAO = FF.CD_FUNDACAO
       AND FN.NUM_INSCRICAO = FF.NUM_INSCRICAO
    INNER JOIN TB_EMPRESA_PLANOS EP ON EP.CD_FUNDACAO = FF.CD_FUNDACAO
       AND EP.CD_EMPRESA = FN.CD_EMPRESA
       AND EP.CD_PLANO   = FF.CD_PLANO
    LEFT OUTER JOIN TB_IND_VALORES IV ON IV.COD_IND = EP.IND_RESERVA_POUP
    LEFT OUTER JOIN TB_IND_VALORES IVA ON IVA.COD_IND = EP.IND_RESERVA_POUP
WHERE FF.CD_FUNDACAO   = @CD_FUNDACAO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.CD_PLANO      = @CD_PLANO
  AND FF.ANO_REF * 13 + FF.MES_REF >= @ANO_INI * 13 + @MES_INI 
  AND FF.ANO_REF * 13 + FF.MES_REF <= @ANO_REF * 13 + @MES_REF   
  AND IV.DT_IND = (SELECT MAX(IV2.DT_IND)
                     FROM TB_IND_VALORES IV2
                    WHERE IV2.COD_IND = IV.COD_IND
                      AND CAST(MONTH(IV2.DT_IND) AS INT) = CAST(FF.MES_REF AS INT)
                      AND CAST(YEAR(IV2.DT_IND) AS INT)  = CAST(FF.ANO_REF AS INT))                                
  AND IVA.DT_IND = (SELECT MAX(IV3.DT_IND)
                     FROM TB_IND_VALORES IV3
                    WHERE IV3.COD_IND = IVA.COD_IND
                      AND MONTH(IV3.DT_IND) = MONTH(DATEADD(MONTH, -1, DATEFROMPARTS(CAST(FF.ANO_REF AS INT) , CAST(FF.MES_REF AS INT), 1 )))
                      AND YEAR(IV3.DT_IND)  = YEAR(DATEADD(MONTH, -1, DATEFROMPARTS(CAST(FF.ANO_REF AS INT) , CAST(FF.MES_REF AS INT), 1 ))))  
GROUP BY FF.CD_FUNDACAO,
         FF.NUM_INSCRICAO,
         FF.CD_PLANO,
         FF.ANO_REF,
         FF.MES_REF
ORDER BY FF.ANO_REF DESC,
         FF.MES_REF DESC