/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_PLANO:string
		-ANO_REF:string
		-MES_REF:string
		-ANO_INI:string
		-MES_INI:string
*/

SELECT FF.CD_FUNDACAO,
       FF.NUM_INSCRICAO,
       FF.CD_PLANO,
       FF.ANO_REF,
       FF.MES_REF,
       FF.ANO_COMP,
       FF.MES_COMP,
       TC.DS_TIPO_CONTRIBUICAO,
       FF.CD_OPERACAO,
       ISNULL(CASE WHEN FF.CD_OPERACAO = 'D' THEN FF.CONTRIB_PARTICIPANTE * -1 ELSE FF.CONTRIB_PARTICIPANTE END,0) AS CONTRIB_PARTICIPANTE,
       ISNULL(CASE WHEN FF.CD_OPERACAO = 'D' THEN FF.CONTRIB_EMPRESA * -1 ELSE FF.CONTRIB_EMPRESA END,0) AS CONTRIB_EMPRESA,
       ISNULL(CASE WHEN FF.CD_OPERACAO = 'D' THEN FF.QTD_COTA_RP_PARTICIPANTE * -1 ELSE FF.QTD_COTA_RP_PARTICIPANTE END,0) AS QTD_COTA_RP_PARTICIPANTE,
       ISNULL(CASE WHEN FF.CD_OPERACAO = 'D' THEN FF.QTD_COTA_RP_EMPRESA * -1 ELSE FF.QTD_COTA_RP_EMPRESA END,0) AS QTD_COTA_RP_EMPRESA,
       ISNULL(FF.SRC, 0) AS SRC
FROM CC_FICHA_FINANCEIRA FF
    INNER JOIN TB_TIPO_CONTRIBUICAO TC ON TC.CD_TIPO_CONTRIBUICAO = FF.CD_TIPO_CONTRIBUICAO
    INNER JOIN CS_FUNCIONARIO FN ON FN.CD_FUNDACAO = FF.CD_FUNDACAO
       AND FN.NUM_INSCRICAO = FF.NUM_INSCRICAO
    INNER JOIN TB_EMPRESA_PLANOS EP ON EP.CD_FUNDACAO = FF.CD_FUNDACAO
       AND EP.CD_EMPRESA = FN.CD_EMPRESA
       AND EP.CD_PLANO   = FF.CD_PLANO
WHERE FF.CD_FUNDACAO   = @CD_FUNDACAO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.CD_PLANO      = @CD_PLANO
  AND FF.ANO_REF * 13 + FF.MES_REF >= @ANO_INI * 13 + @MES_INI 
  AND FF.ANO_REF * 13 + FF.MES_REF <= @ANO_REF * 13 + @MES_REF 
  AND TC.COMPOE_SALDO_BENEFICIO = 'S'
ORDER BY FF.ANO_REF DESC,
         FF.MES_REF DESC,
         TC.DS_TIPO_CONTRIBUICAO