/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_PLANO:string
        -NUM_INSCRICAO:string
        -ANO_REF:string
        -MES_REF:string
*/

SELECT *
 FROM CC_FICHA_FINANCEIRA FI
INNER JOIN TB_TIPO_CONTRIBUICAO TC ON  TC.CD_TIPO_CONTRIBUICAO = FI.CD_TIPO_CONTRIBUICAO
WHERE FI.CD_FUNDACAO = @CD_FUNDACAO
  AND FI.CD_PLANO = @CD_PLANO
  AND FI.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FI.ANO_REF = @ANO_REF
  AND FI.MES_REF = @MES_REF
ORDER BY TC.CD_TIPO_CONTRIBUICAO