/*Config
    RetornaLista
    Retorno
        -FichaFinanceiraEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_PLANO:string
        -NUM_INSCRICAO:string
        -ANO_REF:string
        -MES_REF:string
*/

SELECT DISTINCT 
       TC.DS_TIPO_CONTRIBUICAO,
       TC.CD_TIPO_CONTRIBUICAO,
       SUM(FI.CONTRIB_PARTICIPANTE) AS CONTRIB_PARTICIPANTE,
       SUM(FI.CONTRIB_EMPRESA) AS CONTRIB_EMPRESA,
       0 + SUM(FI.CONTRIB_PARTICIPANTE) + SUM(FI.CONTRIB_EMPRESA) AS TOTAL_CONTRIB,
       0 + SUM(FI.QTD_COTA_RP_PARTICIPANTE) + SUM(FI.QTD_COTA_RP_EMPRESA) AS QTD_COTA
 FROM CC_FICHA_FINANCEIRA FI
INNER JOIN TB_TIPO_CONTRIBUICAO TC ON  TC.CD_TIPO_CONTRIBUICAO = FI.CD_TIPO_CONTRIBUICAO
WHERE FI.CD_FUNDACAO = @CD_FUNDACAO
  AND FI.CD_PLANO = @CD_PLANO
  AND FI.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FI.ANO_REF = @ANO_REF
  AND FI.MES_REF = @MES_REF
GROUP BY TC.DS_TIPO_CONTRIBUICAO, 
    TC.CD_TIPO_CONTRIBUICAO
ORDER BY TC.CD_TIPO_CONTRIBUICAO