#region Usings
using Dapper;
using Intech.Lib.Dapper;
using Intech.Lib.Web;
using Intech.PrevSystem.Entidades;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
#endregion

namespace Intech.PrevSystem.Dados.DAO
{   
    public abstract class WebRecadPublicoAlvoDAO : BaseDAO<WebRecadPublicoAlvoEntidade>
    {
        
		public virtual IEnumerable<WebRecadParticipanteDadosEntidade> BuscarDadosPorCdFundacaoSeqRecebedor(string CD_FUNDACAO, decimal SEQ_RECEBEDOR)
		{
			try
			{
				if(AppSettings.IS_SQL_SERVER_PROVIDER)
					return Conexao.Query<WebRecadParticipanteDadosEntidade>("SELECT RB.CD_FUNDACAO,         RB.SEQ_RECEBEDOR,         RB.NUM_INSCRICAO,          RB.CD_EMPRESA,          EE_EMP.SIGLA_ENTID AS NOM_EMPRESA,         RB.NUM_MATRICULA,          EE.NOME_ENTID,         DP.DT_NASCIMENTO,         EE.CPF_CGC,         DP.NU_IDENT,         DP.ORG_EMIS_IDENT,         DP.DT_EMIS_IDENT,         DP.NATURALIDADE,         DP.UF_NATURALIDADE,         DP.NOME_MAE,         DP.NOME_PAI,         DP.CD_ESTADO_CIVIL,         DP.NOME_CONJUGE,         DP.CPF_CONJUGE,         EE.CEP_ENTID,         EE.END_ENTID,         EE.NR_END_ENTID,         EE.COMP_END_ENTID,         EE.BAIRRO_ENTID,         EE.CID_ENTID,         EE.UF_ENTID,                DP.CD_PAIS,         DP.EMAIL_AUX,         DP.FONE_CELULAR,         EE.FONE_ENTID,         EE.NUM_BANCO,         EE.NUM_AGENCIA,         EE.NUM_CONTA,         EE.POLIT_EXP           FROM GB_RECEBEDOR_BENEFICIO RB       INNER JOIN EE_ENTIDADE EE ON EE.COD_ENTID = RB.COD_ENTID      INNER JOIN CS_DADOS_PESSOAIS DP ON DP.COD_ENTID = RB.COD_ENTID      INNER JOIN TB_EMPRESA EP ON EP.CD_FUNDACAO = RB.CD_FUNDACAO AND EP.CD_EMPRESA = RB.CD_EMPRESA      INNER JOIN EE_ENTIDADE EE_EMP ON EE_EMP.COD_ENTID = EP.COD_ENTID  WHERE RB.CD_FUNDACAO = @CD_FUNDACAO    AND RB.SEQ_RECEBEDOR = @SEQ_RECEBEDOR", new { CD_FUNDACAO, SEQ_RECEBEDOR });
				else if(AppSettings.IS_ORACLE_PROVIDER)
					return Conexao.Query<WebRecadParticipanteDadosEntidade>("SELECT RB.CD_FUNDACAO, RB.SEQ_RECEBEDOR, RB.NUM_INSCRICAO, RB.CD_EMPRESA, EE_EMP.SIGLA_ENTID AS NOM_EMPRESA, RB.NUM_MATRICULA, EE.NOME_ENTID, DP.DT_NASCIMENTO, EE.CPF_CGC, DP.NU_IDENT, DP.ORG_EMIS_IDENT, DP.DT_EMIS_IDENT, DP.NATURALIDADE, DP.UF_NATURALIDADE, DP.NOME_MAE, DP.NOME_PAI, DP.CD_ESTADO_CIVIL, DP.NOME_CONJUGE, DP.CPF_CONJUGE, EE.CEP_ENTID, EE.END_ENTID, EE.NR_END_ENTID, EE.COMP_END_ENTID, EE.BAIRRO_ENTID, EE.CID_ENTID, EE.UF_ENTID, DP.CD_PAIS, DP.EMAIL_AUX, DP.FONE_CELULAR, EE.FONE_ENTID, EE.NUM_BANCO, EE.NUM_AGENCIA, EE.NUM_CONTA, EE.POLIT_EXP FROM GB_RECEBEDOR_BENEFICIO  RB  INNER  JOIN EE_ENTIDADE   EE  ON EE.COD_ENTID=RB.COD_ENTID INNER  JOIN CS_DADOS_PESSOAIS   DP  ON DP.COD_ENTID=RB.COD_ENTID INNER  JOIN TB_EMPRESA   EP  ON EP.CD_FUNDACAO=RB.CD_FUNDACAO AND EP.CD_EMPRESA=RB.CD_EMPRESA INNER  JOIN EE_ENTIDADE   EE_EMP  ON EE_EMP.COD_ENTID=EP.COD_ENTID WHERE RB.CD_FUNDACAO=:CD_FUNDACAO AND RB.SEQ_RECEBEDOR=:SEQ_RECEBEDOR", new { CD_FUNDACAO, SEQ_RECEBEDOR });
				else
					throw new Exception("Provider não suportado!");
			}
			finally
			{
				Conexao.Close();
			}
		}

		public virtual IEnumerable<PlanoEntidade> BuscarPlanoPorCdFundacaoSeqRecebedor(string CD_FUNDACAO, decimal SEQ_RECEBEDOR)
		{
			try
			{
				if(AppSettings.IS_SQL_SERVER_PROVIDER)
					return Conexao.Query<PlanoEntidade>("SELECT PL.DS_PLANO,         EB.DS_ESPECIE,  	   PL.CD_PLANO    FROM GB_PROCESSOS_BENEFICIO PB      INNER JOIN GB_RECEBEDOR_BENEFICIO RB ON RB.CD_FUNDACAO = PB.CD_FUNDACAO AND RB.NUM_INSCRICAO = PB.NUM_INSCRICAO      INNER JOIN TB_PLANOS PL ON PL.CD_FUNDACAO = PB.CD_FUNDACAO AND PL.CD_PLANO= PB.CD_PLANO      INNER JOIN GB_ESPECIE_BENEFICIO EB ON EB.CD_ESPECIE = PB.CD_ESPECIE  WHERE RB.CD_FUNDACAO = @CD_FUNDACAO    AND RB.SEQ_RECEBEDOR = @SEQ_RECEBEDOR    AND ( (RB.CD_TIPO_RECEBEDOR = 'A' AND EB.CD_GRUPO_ESPECIE IN ('1','3'))         OR (RB.CD_TIPO_RECEBEDOR = 'G' AND EB.CD_GRUPO_ESPECIE IN ('2','4')))  	   AND PB.CD_SITUACAO NOT IN ('03', '04', '06')", new { CD_FUNDACAO, SEQ_RECEBEDOR });
				else if(AppSettings.IS_ORACLE_PROVIDER)
					return Conexao.Query<PlanoEntidade>("SELECT PL.DS_PLANO, EB.DS_ESPECIE, PL.CD_PLANO FROM GB_PROCESSOS_BENEFICIO  PB  INNER  JOIN GB_RECEBEDOR_BENEFICIO   RB  ON RB.CD_FUNDACAO=PB.CD_FUNDACAO AND RB.NUM_INSCRICAO=PB.NUM_INSCRICAO INNER  JOIN TB_PLANOS   PL  ON PL.CD_FUNDACAO=PB.CD_FUNDACAO AND PL.CD_PLANO=PB.CD_PLANO INNER  JOIN GB_ESPECIE_BENEFICIO   EB  ON EB.CD_ESPECIE=PB.CD_ESPECIE WHERE RB.CD_FUNDACAO=:CD_FUNDACAO AND RB.SEQ_RECEBEDOR=:SEQ_RECEBEDOR AND ((RB.CD_TIPO_RECEBEDOR='A' AND EB.CD_GRUPO_ESPECIE IN ('1', '3')) OR (RB.CD_TIPO_RECEBEDOR='G' AND EB.CD_GRUPO_ESPECIE IN ('2', '4'))) AND PB.CD_SITUACAO NOT  IN ('03', '04', '06')", new { CD_FUNDACAO, SEQ_RECEBEDOR });
				else
					throw new Exception("Provider não suportado!");
			}
			finally
			{
				Conexao.Close();
			}
		}

		public virtual IEnumerable<WebRecadPublicoAlvoEntidade> BuscarPorCpfDataAtual(string CPF, DateTime DATA_ATUAL)
		{
			try
			{
				if(AppSettings.IS_SQL_SERVER_PROVIDER)
					return Conexao.Query<WebRecadPublicoAlvoEntidade>("SELECT PA.*, CA.DTA_TERMINO, RB.CD_TIPO_RECEBEDOR    FROM WEB_RECAD_PUBLICO_ALVO PA      INNER JOIN GB_RECEBEDOR_BENEFICIO RB ON RB.CD_FUNDACAO = PA.CD_FUNDACAO        AND RB.SEQ_RECEBEDOR = PA.SEQ_RECEBEDOR      INNER JOIN EE_ENTIDADE EE ON EE.COD_ENTID = RB.COD_ENTID      INNER JOIN WEB_RECAD_CAMPANHA CA ON CA.OID_RECAD_CAMPANHA = PA.OID_RECAD_CAMPANHA  WHERE EE.CPF_CGC = @CPF    AND CA.DTA_INICIO <= @DATA_ATUAL    AND CA.DTA_TERMINO >= @DATA_ATUAL    AND CA.IND_ATIVO = 'SIM'    ORDER BY DTA_INICIO DESC", new { CPF, DATA_ATUAL });
				else if(AppSettings.IS_ORACLE_PROVIDER)
					return Conexao.Query<WebRecadPublicoAlvoEntidade>("SELECT PA.*, CA.DTA_TERMINO, RB.CD_TIPO_RECEBEDOR FROM WEB_RECAD_PUBLICO_ALVO  PA  INNER  JOIN GB_RECEBEDOR_BENEFICIO   RB  ON RB.CD_FUNDACAO=PA.CD_FUNDACAO AND RB.SEQ_RECEBEDOR=PA.SEQ_RECEBEDOR INNER  JOIN EE_ENTIDADE   EE  ON EE.COD_ENTID=RB.COD_ENTID INNER  JOIN WEB_RECAD_CAMPANHA   CA  ON CA.OID_RECAD_CAMPANHA=PA.OID_RECAD_CAMPANHA WHERE EE.CPF_CGC=:CPF AND CA.DTA_INICIO<=:DATA_ATUAL AND CA.DTA_TERMINO>=:DATA_ATUAL AND CA.IND_ATIVO='SIM' ORDER BY DTA_INICIO DESC", new { CPF, DATA_ATUAL });
				else
					throw new Exception("Provider não suportado!");
			}
			finally
			{
				Conexao.Close();
			}
		}

    }
}
