/*Config
    RetornaLista
    Retorno
        -DependenteEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
		-NUM_SEQ_GR_FAMIL:decimal
*/

SELECT DEP.CD_FUNDACAO,
       DEP.NUM_INSCRICAO,
       DEP.NUM_SEQ_DEP,
       GP.DS_GRAU_PARENTESCO,
       GP.CD_GRAU_PARENTESCO,
       DEP.NOME_DEP,
       DEP.DT_NASC_DEP,
       DEP.SEXO_DEP,
       DEP.CPF,
       DEP.PERC_PECULIO,
	   DEP.CD_PLANO,
	   BP.DT_TERMINO_VALIDADE,
	   BP.NUM_SEQ_GR_FAMIL
FROM GB_BENEFICIARIO_PREVIDENCIAL BP
  INNER JOIN CS_DEPENDENTE DEP ON DEP.CD_FUNDACAO = BP.CD_FUNDACAO
	AND DEP.NUM_INSCRICAO = BP.NUM_INSCRICAO
	AND DEP.NUM_SEQ_DEP = BP.NUM_SEQ_DEP
  INNER JOIN TB_GRAU_PARENTESCO GP ON GP.CD_GRAU_PARENTESCO = DEP.CD_GRAU_PARENTESCO
WHERE BP.CD_FUNDACAO = @CD_FUNDACAO
  AND BP.NUM_INSCRICAO = @NUM_INSCRICAO
  AND BP.NUM_SEQ_GR_FAMIL = @NUM_SEQ_GR_FAMIL
ORDER BY GP.TIPO_VALIDADE DESC