/*Config
    RetornaLista
    Retorno
        -DependenteEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_PLANO:string
		-DATA_ATUAL:DateTime
*/

SELECT CS_DEPENDENTE.*,
    TB_GRAU_PARENTESCO.DS_GRAU_PARENTESCO,
    CS_MOT_PERDA_VALIDADE.DS_MOT_PERDA_VALIDADE,
    CS_FUNCIONARIO.NUM_MATRICULA,
    CS_FUNCIONARIO.CD_EMPRESA,
    EMPRESA.NOME_ENTID AS DS_EMPRESA
 FROM CS_DEPENDENTE
INNER JOIN TB_GRAU_PARENTESCO ON TB_GRAU_PARENTESCO.CD_GRAU_PARENTESCO = CS_DEPENDENTE.CD_GRAU_PARENTESCO
LEFT OUTER JOIN CS_MOT_PERDA_VALIDADE ON CS_MOT_PERDA_VALIDADE.CD_MOT_PERDA_VALIDADE = CS_DEPENDENTE.CD_MOT_PERDA_VALIDADE
INNER JOIN CS_FUNCIONARIO ON CS_FUNCIONARIO.NUM_INSCRICAO = CS_DEPENDENTE.NUM_INSCRICAO
INNER JOIN TB_EMPRESA ON TB_EMPRESA.CD_EMPRESA = CS_FUNCIONARIO.CD_EMPRESA
INNER JOIN EE_ENTIDADE EMPRESA ON EMPRESA.COD_ENTID = TB_EMPRESA.COD_ENTID
WHERE CS_DEPENDENTE.CD_FUNDACAO = @CD_FUNDACAO
  AND CS_DEPENDENTE.NUM_INSCRICAO = @NUM_INSCRICAO
  AND CS_DEPENDENTE.CD_PLANO = @CD_PLANO
  AND CS_DEPENDENTE.DT_VALIDADE_DEP >= @DATA_ATUAL
ORDER BY CS_DEPENDENTE.NOME_DEP