/*Config
    RetornaLista
    Retorno
        -DependenteEntidade
    Parametros
        -CD_FUNDACAO:string
        -SEQ_RECEBEDOR:decimal
		-DATA_ATUAL:DateTime
*/

SELECT DEP.CD_FUNDACAO,
       DEP.NUM_INSCRICAO,
       DEP.NUM_SEQ_DEP,
	   GP.CD_GRAU_PARENTESCO,
       GP.DS_GRAU_PARENTESCO,       
       DEP.NOME_DEP,
       DEP.DT_NASC_DEP,
       DEP.SEXO_DEP,       
       DEP.CPF,
       DEP.DT_TERM_IRRF,
       DEP.PERC_PECULIO,
       RB.SEQ_RECEBEDOR
FROM CS_DEPENDENTE DEP
  INNER JOIN TB_GRAU_PARENTESCO GP ON GP.CD_GRAU_PARENTESCO = DEP.CD_GRAU_PARENTESCO
  INNER JOIN GB_BENEFICIARIO_PREVIDENCIAL BP ON BP.CD_FUNDACAO = DEP.CD_FUNDACAO
      AND BP.NUM_INSCRICAO = DEP.NUM_INSCRICAO
      AND BP.NUM_SEQ_DEP = DEP.NUM_SEQ_DEP
  INNER JOIN GB_RECEBEDOR_BENEFICIO RB ON RB.CD_FUNDACAO = BP.CD_FUNDACAO
      AND RB.NUM_INSCRICAO = BP.NUM_INSCRICAO
      AND RB.NUM_SEQ_GR_FAMIL = BP.NUM_SEQ_GR_FAMIL
WHERE DEP.CD_FUNDACAO = @CD_FUNDACAO
  AND RB.SEQ_RECEBEDOR = @SEQ_RECEBEDOR
  AND DEP.DT_TERM_IRRF >= @DATA_ATUAL
ORDER BY GP.TIPO_VALIDADE DESC  