/*Config
    RetornaLista
    Retorno
        -ProcessoBeneficioEntidade
    Parametros
        -CD_FUNDACAO:string
		-SEQ_RECEBEDOR:decimal
*/

SELECT PB.NUM_PROCESSO_PREV
  FROM GB_PROCESSOS_BENEFICIO PB
    INNER JOIN GB_RECEBEDOR_BENEFICIO RB ON RB.CD_FUNDACAO = PB.CD_FUNDACAO AND RB.NUM_INSCRICAO = PB.NUM_INSCRICAO
    INNER JOIN TB_PLANOS PL ON PL.CD_FUNDACAO = PB.CD_FUNDACAO AND PL.CD_PLANO= PB.CD_PLANO
    INNER JOIN GB_ESPECIE_BENEFICIO EB ON EB.CD_ESPECIE = PB.CD_ESPECIE
WHERE RB.CD_FUNDACAO = @CD_FUNDACAO
  AND RB.SEQ_RECEBEDOR = @SEQ_RECEBEDOR
  AND ( (RB.CD_TIPO_RECEBEDOR = 'A' AND EB.CD_GRUPO_ESPECIE IN ('1','3'))
       OR (RB.CD_TIPO_RECEBEDOR = 'G' AND EB.CD_GRUPO_ESPECIE IN ('2','4')))