/*Config
    Retorno
        -long
    Parametros
		-OID_REQ_BENEFICIO:decimal
		-OID_DESC_AUTORIZADO:decimal
		-IND_AUTORIZADO:string
*/

INSERT INTO WEB_REQ_BENEFICIO_DESC(
	OID_REQ_BENEFICIO,
	OID_DESC_AUTORIZADO,
	IND_AUTORIZADO
)
VALUES(
	@OID_REQ_BENEFICIO,
	@OID_DESC_AUTORIZADO,
	@IND_AUTORIZADO
)