/*Config
    Retorno
        -FuncionarioEntidade
    Parametros
        -CPF:string
*/

SELECT TOP 1 
EE_ENTIDADE.NOME_ENTID,
CS_FUNCIONARIO.* 
FROM CS_FUNCIONARIO 
INNER JOIN EE_ENTIDADE ON EE_ENTIDADE.COD_ENTID = CS_FUNCIONARIO.COD_ENTID 
WHERE EE_ENTIDADE.CPF_CGC = @CPF 
