/*Config
    Retorno
        -void
    Parametros
        -COD_ENTID:decimal
        -SIGLA_ENTID:string
        -NOME_ENTID:string
        -GRP_INVEST:string
        -GRP_ADMINIST:string
        -GRP_PREVI:string
        -GRP_ASSIST:string
        -BANCO:string
        -FUNDACAO:string
        -EMPRESA_SA:string
        -CUSTODIANTE:string
        -CORRETORA:string
        -FORNECEDOR:string
        -PREST_SERV:string
        -PARTICIPANTE:string
        -RECEB_BENEF:string
        -CD_TIPO_CORRESP:string
        -PATROCINADORA:string
        -LOCATARIO:string
        -COD_CUSTOD:string
        -SEGURADORA:string
        -COD_CETIP:string
        -FISIC_JURID:string
        -CPF_CGC:string
        -ISS:string
        -NUM_BANCO:string
        -NUM_AGENCIA:string
        -NUM_CONTA:string
        -END_ENTID:string
        -BAIRRO_ENTID:string
        -CID_ENTID:string
        -UF_ENTID:string
        -CEP_ENTID:string
        -FONE_ENTID:string
        -FAX_ENTID:string
        -CONTA_AUX:string
        -OBS_ENTID:string
        -E_MAIL:string
        -CX_POSTAL:string
        -NR_END_ENTID:string
        -COMP_END_ENTID:string
        -COD_ISIN:string
        -TP_CONTA:string
        -AUTONOMO:string
        -DEPENDENTE:decimal?
        -ISENTO_RETENCAO:string
        -INSCRICAO_INSS:string
        -CBO:string
        -INSCRICAO_ISS:string
        -OBRIG_CONTR:string
        -EMIT_RESP:string
        -SEXO:string
        -DT_NASCIMENTO:DateTime?
        -NATURALIDADE:string
        -NACIONALIDADE:string
        -ESTADO_CIVIL:string
        -NOME_PAI:string
        -NOME_MAE:string
        -CONJUGE:string
        -IDENTIDADE:string
        -ORGAO_EXP:string
        -DT_EXPEDICAO:DateTime?
        -NATUREZA_DOC:string
        -OCUPACAO_PROF:string
        -NIRE:string
        -ATIVIDADE_PRINC:string
        -REPRES_BENEF:string
        -GERA_DES:string
        -CD_EXTERNO:string
        -SIT_PAT_FINANCEIRA:string
        -SIT_PAT_RENDIMENTOS:string
        -PF_ENQUADRAMENTO:string
        -RECEBE_EMAIL:string
        -SENHA:string
        -SENHA_ANT1:string
        -SENHA_ANT2:string
        -SENHA_ANT3:string
        -SENHA_ANT4:string
        -SENHA_ANT5:string
        -POLIT_EXP:string
        -TIPO_PPE:string
        -COD_OCORRENCIA:string
        -COD_CATEGORIA:string
        -NUM_CONTA_SAL:string
        -NUM_BANCO_SAL:string
        -NUM_AGENCIA_SAL:string
        -AG_RISCO:string
        -COD_IMP_PATRIM:string
        -ATIVO:string
        -TP_REGIME_TRIBUTACAO:decimal?
        -IND_TIPO_CONTA:string
        -E_MAIL_CONTATO:string
        -BLOQUEADA:string
        -NUM_TENTATIVAS:decimal?
        -DT_EXPIRA:DateTime?
        -NUM_PROX_SENHA_ALT:decimal?
        -PLANO:string
        -CONSOLIDADO:string
        -RECEB_RESGATE:string
        -DEBITO_AUTO:string
        -AUTORIZA_DEB:string
        -NUM_NIF_EFINANCEIRA:string
        -IND_FATCA:string
        -CD_PAIS_EFINANCEIRA:string
        -IND_DESONERA_CPRB:string
*/

INSERT INTO EE_ENTIDADE (
     COD_ENTID
    ,SIGLA_ENTID
    ,NOME_ENTID
    ,GRP_INVEST
    ,GRP_ADMINIST
    ,GRP_PREVI
    ,GRP_ASSIST
    ,BANCO
    ,FUNDACAO
    ,EMPRESA_SA
    ,CUSTODIANTE
    ,CORRETORA
    ,FORNECEDOR
    ,PREST_SERV
    ,PARTICIPANTE
    ,RECEB_BENEF
    ,CD_TIPO_CORRESP
    ,PATROCINADORA
    ,LOCATARIO
    ,COD_CUSTOD
    ,SEGURADORA
    ,COD_CETIP
    ,FISIC_JURID
    ,CPF_CGC
    ,ISS
    ,NUM_BANCO
    ,NUM_AGENCIA
    ,NUM_CONTA
    ,END_ENTID
    ,BAIRRO_ENTID
    ,CID_ENTID
    ,UF_ENTID
    ,CEP_ENTID
    ,FONE_ENTID
    ,FAX_ENTID
    ,CONTA_AUX
    ,OBS_ENTID
    ,E_MAIL
    ,CX_POSTAL
    ,NR_END_ENTID
    ,COMP_END_ENTID
    ,COD_ISIN
    ,TP_CONTA
    ,AUTONOMO
    ,DEPENDENTE
    ,ISENTO_RETENCAO
    ,INSCRICAO_INSS
    ,CBO
    ,INSCRICAO_ISS
    ,OBRIG_CONTR
    ,EMIT_RESP
    ,SEXO
    ,DT_NASCIMENTO
    ,NATURALIDADE
    ,NACIONALIDADE
    ,ESTADO_CIVIL
    ,NOME_PAI
    ,NOME_MAE
    ,CONJUGE
    ,IDENTIDADE
    ,ORGAO_EXP
    ,DT_EXPEDICAO
    ,NATUREZA_DOC
    ,OCUPACAO_PROF
    ,NIRE
    ,ATIVIDADE_PRINC
    ,REPRES_BENEF
    ,GERA_DES
    ,CD_EXTERNO
    ,SIT_PAT_FINANCEIRA
    ,SIT_PAT_RENDIMENTOS
    ,PF_ENQUADRAMENTO
    ,RECEBE_EMAIL
    ,SENHA
    ,SENHA_ANT1
    ,SENHA_ANT2
    ,SENHA_ANT3
    ,SENHA_ANT4
    ,SENHA_ANT5
    ,POLIT_EXP
    ,TIPO_PPE
    ,COD_OCORRENCIA
    ,COD_CATEGORIA
    ,NUM_CONTA_SAL
    ,NUM_BANCO_SAL
    ,NUM_AGENCIA_SAL
    ,AG_RISCO
    ,COD_IMP_PATRIM
    ,ATIVO
    ,TP_REGIME_TRIBUTACAO
    ,IND_TIPO_CONTA
    ,E_MAIL_CONTATO
    ,BLOQUEADA
    ,NUM_TENTATIVAS
    ,DT_EXPIRA
    ,NUM_PROX_SENHA_ALT
    ,PLANO
    ,CONSOLIDADO
    ,RECEB_RESGATE
    ,DEBITO_AUTO
    ,AUTORIZA_DEB
    ,NUM_NIF_EFINANCEIRA
    ,IND_FATCA
    ,CD_PAIS_EFINANCEIRA
    ,IND_DESONERA_CPRB
)
VALUES(
     @COD_ENTID
    ,@SIGLA_ENTID
    ,@NOME_ENTID
    ,@GRP_INVEST
    ,@GRP_ADMINIST
    ,@GRP_PREVI
    ,@GRP_ASSIST
    ,@BANCO
    ,@FUNDACAO
    ,@EMPRESA_SA
    ,@CUSTODIANTE
    ,@CORRETORA
    ,@FORNECEDOR
    ,@PREST_SERV
    ,@PARTICIPANTE
    ,@RECEB_BENEF
    ,@CD_TIPO_CORRESP
    ,@PATROCINADORA
    ,@LOCATARIO
    ,@COD_CUSTOD
    ,@SEGURADORA
    ,@COD_CETIP
    ,@FISIC_JURID
    ,@CPF_CGC
    ,@ISS
    ,@NUM_BANCO
    ,@NUM_AGENCIA
    ,@NUM_CONTA
    ,@END_ENTID
    ,@BAIRRO_ENTID
    ,@CID_ENTID
    ,@UF_ENTID
    ,@CEP_ENTID
    ,@FONE_ENTID
    ,@FAX_ENTID
    ,@CONTA_AUX
    ,@OBS_ENTID
    ,@E_MAIL
    ,@CX_POSTAL
    ,@NR_END_ENTID
    ,@COMP_END_ENTID
    ,@COD_ISIN
    ,@TP_CONTA
    ,@AUTONOMO
    ,@DEPENDENTE
    ,@ISENTO_RETENCAO
    ,@INSCRICAO_INSS
    ,@CBO
    ,@INSCRICAO_ISS
    ,@OBRIG_CONTR
    ,@EMIT_RESP
    ,@SEXO
    ,@DT_NASCIMENTO
    ,@NATURALIDADE
    ,@NACIONALIDADE
    ,@ESTADO_CIVIL
    ,@NOME_PAI
    ,@NOME_MAE
    ,@CONJUGE
    ,@IDENTIDADE
    ,@ORGAO_EXP
    ,@DT_EXPEDICAO
    ,@NATUREZA_DOC
    ,@OCUPACAO_PROF
    ,@NIRE
    ,@ATIVIDADE_PRINC
    ,@REPRES_BENEF
    ,@GERA_DES
    ,@CD_EXTERNO
    ,@SIT_PAT_FINANCEIRA
    ,@SIT_PAT_RENDIMENTOS
    ,@PF_ENQUADRAMENTO
    ,@RECEBE_EMAIL
    ,@SENHA
    ,@SENHA_ANT1
    ,@SENHA_ANT2
    ,@SENHA_ANT3
    ,@SENHA_ANT4
    ,@SENHA_ANT5
    ,@POLIT_EXP
    ,@TIPO_PPE
    ,@COD_OCORRENCIA
    ,@COD_CATEGORIA
    ,@NUM_CONTA_SAL
    ,@NUM_BANCO_SAL
    ,@NUM_AGENCIA_SAL
    ,@AG_RISCO
    ,@COD_IMP_PATRIM
    ,@ATIVO
    ,@TP_REGIME_TRIBUTACAO
    ,@IND_TIPO_CONTA
    ,@E_MAIL_CONTATO
    ,@BLOQUEADA
    ,@NUM_TENTATIVAS
    ,@DT_EXPIRA
    ,@NUM_PROX_SENHA_ALT
    ,@PLANO
    ,@CONSOLIDADO
    ,@RECEB_RESGATE
    ,@DEBITO_AUTO
    ,@AUTORIZA_DEB
    ,@NUM_NIF_EFINANCEIRA
    ,@IND_FATCA
    ,@CD_PAIS_EFINANCEIRA
    ,@IND_DESONERA_CPRB
)