/*Config
    RetornaLista
    Retorno
        -MensagemEntidade
*/

SELECT MSG.*,
	ENT_FUND.NOME_ENTID AS NOM_FUNDACAO,
	ENT_EMP.NOME_ENTID AS NOM_EMPRESA,
	PL.DS_PLANO,
	SIT_PL.DS_SIT_PLANO,
	FUNC.NUM_MATRICULA
FROM WEB_MENSAGEM MSG
INNER JOIN TB_FUNDACAO FUND ON FUND.CD_FUNDACAO = MSG.CD_FUNDACAO
INNER JOIN EE_ENTIDADE ENT_FUND ON ENT_FUND.COD_ENTID = FUND.COD_ENTID

LEFT JOIN TB_EMPRESA EMP ON EMP.CD_EMPRESA = MSG.CD_EMPRESA
LEFT JOIN EE_ENTIDADE ENT_EMP ON ENT_EMP.COD_ENTID = EMP.COD_ENTID

LEFT JOIN TB_PLANOS PL ON PL.CD_PLANO = MSG.CD_PLANO
LEFT JOIN TB_SIT_PLANO SIT_PL ON SIT_PL.CD_SIT_PLANO = MSG.CD_SIT_PLANO
LEFT JOIN CS_FUNCIONARIO FUNC ON FUNC.COD_ENTID = MSG.COD_ENTID

ORDER BY MSG.DTA_MENSAGEM DESC