/*Config
    RetornaLista
    Retorno
        -MensagemEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -CD_PLANO:string
        -CD_SIT_PLANO:string
        -COD_ENTID:string
*/

SELECT MSG.*,
	ENT_FUND.NOME_ENTID AS NOM_FUNDACAO,
	ENT_EMP.NOME_ENTID AS NOM_EMPRESA,
	PL.DS_PLANO,
	SIT_PL.DS_SIT_PLANO,
	FUNC.NUM_MATRICULA
FROM WEB_MENSAGEM MSG
INNER JOIN TB_FUNDACAO FUND ON FUND.CD_FUNDACAO = MSG.CD_FUNDACAO
INNER JOIN EE_ENTIDADE ENT_FUND ON ENT_FUND.COD_ENTID = FUND.COD_ENTID

LEFT JOIN TB_EMPRESA EMP ON EMP.CD_EMPRESA = MSG.CD_EMPRESA
LEFT JOIN EE_ENTIDADE ENT_EMP ON ENT_EMP.COD_ENTID = EMP.COD_ENTID

LEFT JOIN TB_PLANOS PL ON PL.CD_PLANO = MSG.CD_PLANO
LEFT JOIN TB_SIT_PLANO SIT_PL ON SIT_PL.CD_SIT_PLANO = MSG.CD_SIT_PLANO
LEFT JOIN CS_FUNCIONARIO FUNC ON FUNC.COD_ENTID = MSG.COD_ENTID
WHERE (MSG.CD_FUNDACAO = @CD_FUNDACAO)
  AND ((MSG.CD_EMPRESA = @CD_EMPRESA) OR (@CD_EMPRESA IS NULL OR MSG.CD_EMPRESA IS NULL))
  AND ((MSG.CD_PLANO = @CD_PLANO) OR (@CD_PLANO IS NULL OR MSG.CD_PLANO IS NULL))
  AND ((MSG.CD_SIT_PLANO = @CD_SIT_PLANO) OR (@CD_SIT_PLANO IS NULL OR MSG.CD_SIT_PLANO IS NULL))
  AND ((MSG.COD_ENTID = @COD_ENTID) OR (MSG.COD_ENTID IS NULL))