/*Config
    Retorno
        -long
    Parametros
        -OID_RECAD_DADOS: decimal
		-NUM_SEQ_DEP: decimal
		-NOM_DEPENDENTE: string
		-COD_GRAU_PARENTESCO: string
		-DES_GRAU_PARENTESCO: string
		-DTA_NASCIMENTO: DateTime?
		-DTA_INICIO_IRRF: DateTime?
		-DTA_TERMINO_IRRF: DateTime?
		-COD_SEXO: string
		-DES_SEXO: string
		-COD_CPF: string
		-IND_OPERACAO: string
*/

INSERT INTO WEB_RECAD_DEPENDENTE_IR(
	OID_RECAD_DADOS,
    NUM_SEQ_DEP,
    NOM_DEPENDENTE,
    COD_GRAU_PARENTESCO,
    DES_GRAU_PARENTESCO,
    DTA_NASCIMENTO,
    DTA_INICIO_IRRF,
    DTA_TERMINO_IRRF,
    COD_SEXO,
    DES_SEXO,
    COD_CPF,
    IND_OPERACAO
)
VALUES(
    @OID_RECAD_DADOS,
    @NUM_SEQ_DEP,
    @NOM_DEPENDENTE,
    @COD_GRAU_PARENTESCO,
    @DES_GRAU_PARENTESCO,
    @DTA_NASCIMENTO,
    @DTA_INICIO_IRRF,
    @DTA_TERMINO_IRRF,
    @COD_SEXO,
    @DES_SEXO,
    @COD_CPF,
    @IND_OPERACAO
)