/*Config
    RetornaLista
    Retorno
        -NaturezaEntidade
    Parametros
        -CD_MODAL:decimal
        -CD_PLANO:string
        -ATIVO:string
        -ASSISTIDO:string
        -AUTOPATROCINADO:string
        -DIFERIDO:string
*/

SELECT CE_NATUREZA.*
FROM CE_NATUREZA
INNER JOIN CE_GRUPO_NATUREZA ON CE_GRUPO_NATUREZA.CD_GRUPO = CE_NATUREZA.CD_GRUPO
INNER JOIN CE_MODALIDADE ON CE_MODALIDADE.CD_MODAL = CE_GRUPO_NATUREZA.CD_MODAL
WHERE CE_MODALIDADE.CD_MODAL = @CD_MODAL
  AND (CE_GRUPO_NATUREZA.CD_PLANO = @CD_PLANO OR @CD_PLANO IS NULL)
  AND (CE_NATUREZA.SITUACAO = 'A')
  AND (CE_NATUREZA.CATEGORIA_ATIVO = @ATIVO OR @ATIVO IS NULL)
  AND (CE_NATUREZA.CATEGORIA_ASSISTIDO = @ASSISTIDO OR @ASSISTIDO IS NULL)
  AND (CE_NATUREZA.CATEGORIA_AUTOPATROCINADO = @AUTOPATROCINADO OR @AUTOPATROCINADO IS NULL)
  AND (CE_NATUREZA.CATEGORIA_DIFERIDO = @DIFERIDO OR @DIFERIDO IS NULL)
ORDER BY PRAZO_MIN