/*Config
    RetornaLista
    Retorno
        -NaturezaEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -CD_PLANO:string
        -CD_MODAL:decimal
*/

SELECT DISTINCT CE_NATUREZA.*,
                CE_GRUPO_NATUREZA.CD_PLANO,
                CE_MODALIDADE.DS_MODAL,
                CE_NATUREZA.ID_TEMP_VINC,
                CE_NATUREZA.PERMITE_CONCESSAO_WEB
FROM CE_GRUPO_NATUREZA
INNER JOIN CE_MODALIDADE ON CE_MODALIDADE.CD_MODAL = CE_GRUPO_NATUREZA.CD_MODAL
INNER JOIN CE_NATUREZA ON CE_NATUREZA.CD_GRUPO = CE_GRUPO_NATUREZA.CD_GRUPO
INNER JOIN CE_TAXAS_ENCARGOS_PLANO ON CE_TAXAS_ENCARGOS_PLANO.CD_NATUR = CE_NATUREZA.CD_NATUR
AND CE_TAXAS_ENCARGOS_PLANO.CD_MODAL = CE_MODALIDADE.CD_MODAL
INNER JOIN CE_TAXAS_CONCESSAO_PLANO ON CE_TAXAS_CONCESSAO_PLANO.CD_NATUR = CE_NATUREZA.CD_NATUR
AND CE_TAXAS_ENCARGOS_PLANO.SEQUENCIA = CE_TAXAS_CONCESSAO_PLANO.SEQUENCIA
WHERE (CE_MODALIDADE.SITUACAO = 'A')
  AND (CE_NATUREZA.SITUACAO = 'A')
  AND (CE_NATUREZA.AUTORIZACAO_ESPECIAL = 'N')
  AND (CE_MODALIDADE.CD_MODAL = @CD_MODAL)
  AND (CE_NATUREZA.PERMITE_CONCESSAO_WEB = 'S')
  AND (CE_TAXAS_CONCESSAO_PLANO.CD_FUNDACAO = @CD_FUNDACAO)
  AND (CE_TAXAS_ENCARGOS_PLANO.CD_FUNDACAO = @CD_FUNDACAO)
  AND (CE_TAXAS_ENCARGOS_PLANO.CD_EMPRESA = @CD_EMPRESA)
  AND (CE_TAXAS_CONCESSAO_PLANO.CD_EMPRESA = @CD_EMPRESA)
  AND (CE_TAXAS_ENCARGOS_PLANO.DT_INIC_VIGENCIA =
         (SELECT MAX(DT_INIC_VIGENCIA) AS Expr1
          FROM CE_TAXAS_ENCARGOS_PLANO AS CE_TAXAS_ENCARGOS_AUX
          WHERE (CD_FUNDACAO = @CD_FUNDACAO)
            AND (CD_EMPRESA = @CD_EMPRESA)
            AND (CD_MODAL = CE_MODALIDADE.CD_MODAL)
            AND (CD_PLANO = CE_TAXAS_CONCESSAO_PLANO.CD_PLANO)
            AND (DT_INIC_VIGENCIA <= GETDATE())))
  AND (CE_TAXAS_ENCARGOS_PLANO.CD_PLANO = @CD_PLANO)
  AND (CE_TAXAS_CONCESSAO_PLANO.CD_PLANO = @CD_PLANO)
ORDER BY CE_NATUREZA.CD_NATUR
