/*Config
    RetornaLista
    Retorno
        -BloqueioEntidade
    Parametros
        -COD_ENTID:string
*/

SELECT * 
FROM CS_BLOQUEIO
INNER JOIN TB_TIPO_BLOQUEIO ON TB_TIPO_BLOQUEIO.CD_TIPO_BLOQUEIO = CS_BLOQUEIO.CD_TIPO_BLOQUEIO
WHERE TB_TIPO_BLOQUEIO.BLOQUEIO_EM = 'S'
  AND CS_BLOQUEIO.COD_ENTID = @COD_ENTID