using System;
using System.Collections.Generic;
using Dapper.Contrib.Extensions;

namespace Intech.PrevSystem.Entidades
{
	[Table("TB_EMPRESA_PLANOS")]
	public class EmpresaPlanosEntidade
	{
		public string CD_FUNDACAO { get; set; }
		public string CD_EMPRESA { get; set; }
		public string CD_PLANO { get; set; }
		public DateTime? DT_IMPLANTACAO { get; set; }
		public DateTime? PRAZO_FUNDADOR { get; set; }
		public string TIPO_RATEIO_CTFAM { get; set; }
		public decimal? PERC_BASE_CTFAM { get; set; }
		public decimal? PERC_CTIND_CTFAM { get; set; }
		public decimal? PERC_MAX_CTFAM { get; set; }
		public string EXCLUI_DEP_CTFAM { get; set; }
		public string CD_MOEDA_RMENSAL { get; set; }
		public string CD_MOEDA_CMONET { get; set; }
		public string CD_MOEDA_VCOTA { get; set; }
		public decimal? PERC_LIQ_MINIMO { get; set; }
		public string REGRA_DESCONTO { get; set; }
		public string CC_TIPO_TABELA { get; set; }
		public string CC_DATA_BASE { get; set; }
		public string CC_BASE_CALCULO { get; set; }
		public string CC_CD_ESPECIES { get; set; }
		public string CC_CONDICAO { get; set; }
		public decimal? TX_MULTA_AP { get; set; }
		public decimal? TX_JMORA_AP { get; set; }
		public string CD_IND_AT_AP { get; set; }
		public decimal? NM_DIA_CAR_AP { get; set; }
		public decimal? TX_MULTA_AS { get; set; }
		public decimal? TX_JMORA_AS { get; set; }
		public string CD_IND_AT_AS { get; set; }
		public decimal? NM_DIA_CAR_AS { get; set; }
		public string MES_DATA_BASE { get; set; }
		public string TIPO_CALC_AB_PREV { get; set; }
		public decimal? CAR_CALC_AB_PREV { get; set; }
		public string TIPO_CALC_AB_FUND { get; set; }
		public decimal? CAR_CALC_AB_FUND { get; set; }
		public decimal? TIPO_FRAC_AB_FUND { get; set; }
		public string CA_DATA_BASE { get; set; }
		public string MES_ATU_CONTRIB { get; set; }
		public string RENDA_VINCULADA { get; set; }
		public string SALARIO_ZERADO { get; set; }
		public string CONTRIB_ZERADA { get; set; }
		public string CONTRIB_PATROC_ZERADA { get; set; }
		public string IND_RESERVA_POUP { get; set; }
		public string IND_FUNDO { get; set; }
		public decimal? VL_PAGTO_ABSURDO { get; set; }
		public string VERIFICA_BENEF_ATIVO { get; set; }
		public string CD_RUB_COB_ASS { get; set; }
		public string TIPO_PAGTO_COTA { get; set; }
		public string DIA_VALORIZ_COTA { get; set; }
		public string CD_RUB_CONTRIB_RMENSAL { get; set; }
		public string CD_RUB_CONTRIB_ABONO { get; set; }
		public string ABONO_INTEGRAL_FUND { get; set; }
		public string ABONO_INTEGRAL_PREV { get; set; }
		public string CALCULA_AB_ANUAL_FUND { get; set; }
		public string CALCULA_AB_ANUAL_PREV { get; set; }
		public decimal? CD_PLANO_CT { get; set; }
		public decimal? QTD_MESES_ID { get; set; }
		public string LIM_PERC_ID { get; set; }
		public string PERMITE_EMPRESTIMO { get; set; }
		public string CD_RUB_PJ_RMENSAL { get; set; }
		public string CD_RUB_PJ_ABONO { get; set; }
		public string CD_MOEDA_CMONET_REV { get; set; }
		public string CD_RUB_REV_POS_RM { get; set; }
		public string CD_RUB_REV_POS_AB { get; set; }
		public string CD_RUB_REV_NEG_RM { get; set; }
		public string CD_RUB_REV_NEG_AB { get; set; }
		public string TIPO_LANC_RECEB { get; set; }
		public string TIPO_LANC_DEVOL { get; set; }
		public decimal? NUM_PARC_RECEB { get; set; }
		public decimal? NUM_PARC_DEVOL { get; set; }
		public string COD_IND_POS { get; set; }
		public string COD_IND_NEG { get; set; }
		public string COD_IND_CC { get; set; }
		public string TIPO_CALCULO_CC { get; set; }
		public decimal? PARC_PERC_VL_CC { get; set; }
		public string QTD_MES_REV { get; set; }
		public string AUTORIZA_ABONO { get; set; }
		public string DESC_MES_ANT_COTA { get; set; }
		public string AUTORIZA_DESC_CONTRIB_REV { get; set; }
		public string RES_MATEM { get; set; }
		public string CD_RUB_ASSISTENCIAL { get; set; }
		public decimal? VL_MARGEM_LIQ_DESC { get; set; }
		public string REAJ_RENDA_ABONO_FUND { get; set; }
		public string IND_PASSIVO { get; set; }
		public DateTime? PRAZO_FUNDADOR_EMP { get; set; }
		public string CD_RUB_CONTRIB_PAT_SDESCM { get; set; }
		public string CD_RUB_CONTRIB_PAT_SDESCA { get; set; }
		public string CD_RUB_CONTRIB_PAT_CDESCM { get; set; }
		public string CD_RUB_CONTRIB_PAT_CDESCA { get; set; }
		public decimal? PERC_CONTRIB_PATRONAL { get; set; }
		public string IND_ANUIDADE { get; set; }
		public string MES_DESC_ANUIDADE { get; set; }
		public string AM_NIVEL_SAL { get; set; }
		public string CD_CONTA_QT_CRED { get; set; }
		public string CD_CONTA_QT_DEB { get; set; }
		public string CD_HISTORICO_QT { get; set; }
		public string CD_HISTORICO_DR_QT { get; set; }
		public string CD_OPER_QT { get; set; }
		public string CD_CONTA_QT_CONTRIB_CRED { get; set; }
		public string CD_CONTA_QT_CONTRIB_DEB { get; set; }
		public string CD_HISTORICO_CONTRIB_QT { get; set; }
		public string CD_OPER_CONTRIB_QT { get; set; }
		public string PP_TX_ADM { get; set; }
		public decimal? VL_MIN_ADIANTAMENTO_ABONO { get; set; }
		public string COD_TP_APLIC { get; set; }
		public decimal? MES_ABONO_ANUAL { get; set; }
		public string IND_RES_MATEM { get; set; }
		public string AD_ABONO_ADQUIRIDO { get; set; }
		public string PORTABILIDADE { get; set; }
		public string UTILIZA_RUB_REVISAO { get; set; }
		public string CD_TIPO_CONTRIBUICAO_RESG_PARC { get; set; }
		public string CORRIGE_RETROAT_COTA { get; set; }
		public string CD_RUB_CORR_RETROAT_COTA_POS { get; set; }
		public string CD_RUB_CORR_RETROAT_COTA_NEG { get; set; }
		public string REAJ_ANIVERSARIO { get; set; }
		public string ABONO_PROC_ANTERIOR { get; set; }
		public string ID_CORR_MONET { get; set; }
		public string CC_CORR_MONET_CONTRIB { get; set; }
		public string CD_RUB_FAT_RENDA_MENSAL { get; set; }
		public string CD_RUB_FAT_ABONO_MENSAL { get; set; }
		public string CD_RUB_FAT_MIN_MENSAL { get; set; }
		public string CD_RUB_FAT_ABONO_ANUAL { get; set; }
		public string CD_COMP_BENEF_ANT_PLANO { get; set; }
		public string IND_REAJ_DIF { get; set; }
		public string MES_REAJUSTE_CD { get; set; }
		public string CALC_SEM_CONTRIB { get; set; }
	}
}
