using System;
using System.Collections.Generic;
using Dapper.Contrib.Extensions;
using Intech.PrevSystem.Entidades.Outros;
namespace Intech.PrevSystem.Entidades
{
	[Table("TB_PARAMETRO_INSTALACAO")]
	public class ParametroInstalacaoEntidade
	{
		public string CD_FUNDACAO { get; set; }
		public string MASCARA_CAUXILIAR { get; set; }
		public string MASCARA_CCONTABIL { get; set; }
		public string ABATE_DEP_RESGATE { get; set; }
		public string FORMATO_DATA { get; set; }
		public string CONV_PREVIDENCIAL { get; set; }
		public string BONUS_SUPLEMENTAR { get; set; }
		public string FATOR_ATUARIAL { get; set; }
		public int? TEMPO_MEDIO_CONTRIB { get; set; }
		public string CD_EMP_ATUARIA { get; set; }
		public string VERSAO_WORD { get; set; }
		public string DIRETORIO_MODELOS { get; set; }
		public int? NUM_CD_CONTABIL { get; set; }
		public string EMITENTE_BOLETA { get; set; }
		public string TIPO_CALENDARIO { get; set; }
		public string DIRETORIO_TRABALHO { get; set; }
		public string CRITERIO_SELECAO { get; set; }
		public string FORMATO_FONE { get; set; }
		public string FORMATO_MATRICULA { get; set; }
		public string NATUREZA_AUTOPAT { get; set; }
		public string NATUREZA_RESGATE { get; set; }
		public string NATUREZA_IR { get; set; }
		public string FORMA_EMIS_CONSIG { get; set; }
		public string FORMA_CONTAB_FOLHA { get; set; }
		public string CS_SOMA_TEMPO { get; set; }
		public string CS_VERSAO { get; set; }
		public string GRAVA_DIF_MOVIMENTO { get; set; }
		public int? CS_SEQ_BOLETA { get; set; }
		public string SUPL_SINTETICA { get; set; }
		public string NEGATIVO_FOLHA { get; set; }
		public string PB_VERSAO { get; set; }
		public string CS_TP_RATEIO { get; set; }
		public string INDICE_PLANO { get; set; }
		public string COMP_BENEF_ANT { get; set; }
		public string RUBRICA_ADIANT { get; set; }
		public string MCONSIG_EMPR_BENEF { get; set; }
		public string INTEGR_FICHA_ATIVO { get; set; }
		public int? NUM_CD_CONTABIL_PB { get; set; }
		public int? CD_SEQ_BOLETA { get; set; }
		public string CONV_CTR_COMP { get; set; }
		public string ATUALIZA_VERSAO { get; set; }
		public decimal? COD_ETIQUETA { get; set; }
		public decimal? DIAS_SUBTRAIR { get; set; }
		public string AM_NUM_BANCO { get; set; }
		public string REF_DIF_COMP { get; set; }
		public string CONTA_CF { get; set; }
		public string TP_DOC { get; set; }
		public string RECALCULA_COBRANCA { get; set; }
		public string CALC_FUNDADOR { get; set; }
		public string EMITENTE_PB { get; set; }
		public string DT_REC_PLA { get; set; }
		public string LANC_FINANC { get; set; }
		public string VALOR_PP { get; set; }
		public string PR_SLD_DEV { get; set; }
		public decimal? RUB_CF_IRRF { get; set; }
		public decimal? RUB_CF_SLD_DEV { get; set; }
		public string NATUR_SLD_DEV { get; set; }
		public string SLD_DEV_CE_RESERVA { get; set; }
		public string QUITAR_CE_RESERVA { get; set; }
		public string ATUALIZA_BASE { get; set; }
		public string TIPO_INTEGR_CF { get; set; }
		public string ORIGEM_NATUREZA { get; set; }
		public string APR_13 { get; set; }
		public string TOTAL_ARREC { get; set; }
		public string FOLHA_ABERTA { get; set; }
		public string PREST_CE { get; set; }
		public string NATUREZA_TIPO_RESG { get; set; }
		public string UTILIZA_CAD_DEP_IRRF { get; set; }
		public string IRRF_SOMADO { get; set; }
		public string UNIFICA_PP { get; set; }
		public string ESPECIE_TMP_SERV { get; set; }
		public string ESPECIE_IDADE { get; set; }
		public string SISTEMA_CF { get; set; }
		public int? CREDOR_PP_PB { get; set; }
		public string GERA_PP_BANCO_PB { get; set; }
		public string GERA_PP_FORMAPAG_PB { get; set; }
		public string EMITENTE_DR { get; set; }
		public string EMITENTE_CA { get; set; }
		public string INTEGRA_DIF_CREDITO { get; set; }
		public string INTEGRA_DIF_DEBITO { get; set; }
		public string IND_VALOR_VARIACAO { get; set; }
		public string COMP_REGRA_CALC { get; set; }
		public decimal? PERC_MIN_RESG { get; set; }
		public string UTILIZA_CS_MESTRE { get; set; }
		public string RUBRICA_5_DIG { get; set; }
		public string PREVISAO_UNICA_CA { get; set; }
		public string UTILIZA_DEP_PREV { get; set; }
		public string RECEB_CF { get; set; }
		public decimal? CD_TIPO_RECADASTRAMENTO { get; set; }
		public string IMPORTA_RUB_AM { get; set; }
		public string CONVENIO_AM_01 { get; set; }
		public string CONVENIO_AM_02 { get; set; }
		public string CONVENIO_AM_03 { get; set; }
		public string ARREDONDA_DR { get; set; }
		public string CONCESSAO_CORR_EMP { get; set; }
		public string DEP_PREV_AUTO { get; set; }
		public string DEP_ASSIST_AUTO { get; set; }
		public string NATUREZA_EMP_CA { get; set; }
		public string MODULO_RESG_PP { get; set; }
		public string CONVENIO_AM_04 { get; set; }
		public string CONVENIO_AM_05 { get; set; }
		public string VALIDA_SIT_PLANO_RESG { get; set; }
		public string DT_PAGTO_FSF { get; set; }
		public string SLD_DEV_CE_PORTABILIDADE { get; set; }
		public string TIPO_DT_IRRF_REGRESSIVO { get; set; }
		public string PROVISAO_ABO_ANU { get; set; }
		public int? SEQ_ARQ_INT_BOL { get; set; }
		public decimal? RUB_CF_IRRF_REGR { get; set; }
		public string NATUREZA_IR_REGR { get; set; }
		public string COTA_COMPARACAO { get; set; }
		public decimal? VL_POLIT_EXP { get; set; }
		public string EXIGE_JUSTIFICATIVA { get; set; }
		public string CONTA_CT_EMP { get; set; }
		public string PROV_CT { get; set; }
		public int? PB_SEQ_BOLETA { get; set; }
		public string DEP_PLANO { get; set; }
		public string ENCERRA_AM { get; set; }
		public string EM_CATEG_SITPLANO { get; set; }
		public string INTGR_ARQ_BRPREV { get; set; }
		public string INTGR_TAB_BRPREV { get; set; }
		public string TAMANHO_CONTA_CONTABIL_13 { get; set; }
		public string TAMANHO_CONTA_CONTABIL_20 { get; set; }
		public string MASC_CONTA_CT_20 { get; set; }
		public string TIPO_INTGR_BRPREV { get; set; }
		public string TIPO_CONTA_CONTABIL { get; set; }
		public string OID_FUNDACAO { get; set; }
		public string CK_EXIGE_SEQ_CPF { get; set; }
		public decimal? CD_EMPRESA_PGA { get; set; }
		public decimal? CD_PLANO_PGA { get; set; }
		public string NATUREZA_PORTABILIDADE_EA { get; set; }
		public string NATUREZA_PORTABILIDADE_EF { get; set; }
		public string ESPECIE_ESPECIAL { get; set; }
		public string ESPECIE_ANTECIPADA { get; set; }
		public string CK_CONCESSAO { get; set; }
		public string CK_VALIDADE_CONTRIB_IND { get; set; }
		public string CK_DT_RECOLHIMENTO_FF { get; set; }
		public string CK_UTILIZA_BPD { get; set; }
		public int? NU_SEQ_COAF { get; set; }
		public string CONTA_PROC { get; set; }
		public string CK_CPF_IR { get; set; }
		public string CK_RUB_ISENCAO_IR_SEP { get; set; }
		public string CK_MENU_CALCULO { get; set; }
		public string CK_CELULAR_NOVE_DIGITOS { get; set; }
		public string CK_COMPARATIVO_INSS { get; set; }
		public string CK_IRRFREGRES_588 { get; set; }
		public string CK_CONSIDERA_DIAS { get; set; }
		public string CK_INDICE_ESPECIAL { get; set; }
		public string CK_REAJ_DIF { get; set; }
		public string CK_INTEGR_CF_PLANO_IRRF { get; set; }
		public string IND_RESERVA_IN1343 { get; set; }
		public string IND_VALIDA_CADASTRO { get; set; }
		public string IND_VALIDA_INDICE { get; set; }
		public string IND_NOVO_FUNDO { get; set; }
		public string IND_ABATE_IN1343 { get; set; }
		public string CK_MASCARA_TEL_UF { get; set; }
		public string CK_RATEIO_IR_PROC { get; set; }
		public string IND_IN1343_PLANO { get; set; }
		public string IND_IN1343_REGRESSIVO { get; set; }
		public string DESC_IRRF_CE_PORTABILIDADE { get; set; }
		public string IND_IN14952014 { get; set; }
		public string ALTERA_FICHA { get; set; }
		public string PROVISAO_ABO_ANU_RUB { get; set; }
		public string IND_CONTABIL_RESGATE { get; set; }
		public string IND_ALT_DATA_DESLIG_INST { get; set; }
		public string ID_PENSAO_CONVERT_IN1343 { get; set; }
		public string IND_ALTERA_COBRANCA { get; set; }
		public string ID_MP_676_2015 { get; set; }
		public string CK_MAT_IR { get; set; }
		public string ID_SALDAR_SEM_IR_IN1343 { get; set; }
		public string ISENTA_REGRESSIVO_65 { get; set; }
		public string PAGTO_ATIVO { get; set; }
		public string EMITENTE_PGA { get; set; }
		public string OID_TESOURARIA { get; set; }
		public string TIPO_RESG_SIT_PLANO { get; set; }
		public string IND_CONTROLE_INADIMPLENCIA { get; set; }
		public string IND_NOVO_CALCULO { get; set; }
		public string CONTRIB_CANC_FICHA { get; set; }
		public string IND_INCLUI_PA_ORIGEM_NAT_RECEB { get; set; }
		public string ID_GRAVA_ABAT_FICHA_ATIVO { get; set; }
		public string ID_TIPO_GRAVA_ABAT_FICHA_ATIVO { get; set; }
		public string ABAT_SALDO_INIC { get; set; }
		public string IND_CALCULO_CANCELADOS { get; set; }
		public string ABATER_RUBR_INCID_SALDO_PARAM { get; set; }
		public string RRA_RRF { get; set; }
		public string IND_DR_CALCULO_UNIFICADO { get; set; }
		public string IND_APORTE_PORT { get; set; }
		public string IND_APORTE_ESP { get; set; }
		public string IND_DESATIVADO { get; set; }
	}
}