using System;
using System.Collections.Generic;
using Dapper.Contrib.Extensions;
using Intech.PrevSystem.Entidades.Outros;
namespace Intech.PrevSystem.Entidades
{
	[Table("GB_REGRA_CALC_FUNDACAO")]
	public class RegraCalcFundacaoEntidade
	{
		public string CD_FUNDACAO { get; set; }
		public string CD_PLANO { get; set; }
		public string CD_ESPECIE { get; set; }
		public DateTime DT_VIGENCIA_FUND { get; set; }
		public string FCALC_FUND_PGU_SOPC { get; set; }
		public string FCALC_FUND_PGU_COPC { get; set; }
		public string FCALC_FUND_BEN_MIN { get; set; }
		public string FCALC_FUND_BEN_MAX { get; set; }
		public string FCALC_FUND_SUPL { get; set; }
		public string MOEDA_SAL_PBC_FUND { get; set; }
		public string MOEDA_LIM_PBC_FUND { get; set; }
		public string MOEDA_COR_PBC_FUND { get; set; }
		public string MOEDA_COR_PBC_EMP { get; set; }
		public string TIPO_SAL_PBC_FUND { get; set; }
		public decimal? NSAL_MIN_PBC_FUND { get; set; }
		public decimal? NSAL_MAX_PBC_FUND { get; set; }
		public string COMPLEMENTAR { get; set; }
		public string EXIGE_CID { get; set; }
		public string ACEITA_TRANSFORMACAO { get; set; }
		public string TIPO_CALC_RM { get; set; }
		public decimal? PERC_MAX_ANTECIP { get; set; }
		public string REVERS_BENEF_RISCO { get; set; }
		public string TIPO_CALC_DIB_FUND { get; set; }
		public decimal? PRAZO_CALC_DIB_FUND { get; set; }
		public decimal? PRAZO_LIMITE_REQ_FUND { get; set; }
		public string PROCED_CALC { get; set; }
		public decimal? MIN_CONTR_MASC { get; set; }
		public decimal? MIN_CONTR_FEM { get; set; }
		public decimal? MIN_CONTR_FUND { get; set; }
		public decimal? TMP_FUND_MASC { get; set; }
		public decimal? TMP_FUND_FEM { get; set; }
		public decimal? TMP_FUND_FUND { get; set; }
		public decimal? TMP_IDADE_FEM { get; set; }
		public decimal? TMP_IDADE_MASC { get; set; }
		public decimal? TMP_IDADE_FUND { get; set; }
		public decimal? TMP_EMP_MASC { get; set; }
		public decimal? TMP_EMP_FEM { get; set; }
		public decimal? TMP_EMP_FUND { get; set; }
		public string FCAL_ASS_BMIN { get; set; }
		public string FCAL_ASS_BMAX { get; set; }
		public string FCAL_ASS_PGU_COP { get; set; }
		public string FCAL_ASS_PGU_SOP { get; set; }
		public string COMP_PBC_ASSIST { get; set; }
		public decimal? TV_ABONO_APOSENT { get; set; }
		public string FCAL_ABONO_APOSENT { get; set; }
		public string FCAL_LIM_AB_APOSENT { get; set; }
		public decimal? CAR_MIN_IDADE_FEM { get; set; }
		public decimal? CAR_MIN_IDADE_MASC { get; set; }
		public decimal? CAR_MIN_VINC_FEM { get; set; }
		public decimal? CAR_MIN_VINC_MASC { get; set; }
		public string FCAL_SRB_MIN { get; set; }
		public string FCAL_SRB_MAX { get; set; }
		public string TP_FATOR_REDUTOR { get; set; }
		public decimal? VL_FATOR_REDUTOR { get; set; }
		public string CONTA_PROVISAO { get; set; }
		public string AUXILIAR_PROVISAO { get; set; }
		public string HISTORICO_PROVISAO { get; set; }
		public string CCUSTO_PROVISAO { get; set; }
		public string CONTA_PROVISAO_DEB { get; set; }
		public string AUXILIAR_PROVISAO_DEB { get; set; }
		public string HISTORICO_PROVISAO_DEB { get; set; }
		public string CCUSTO_PROVISAO_DEB { get; set; }
		public string CONTA_PROV_CONTRIB_CRED { get; set; }
		public string AUXILIAR_PROV_CONTRIB_CRED { get; set; }
		public string HISTORICO_PROV_CONTRIB_CRED { get; set; }
		public string CCUSTO_PROV_CONTRIB_CRED { get; set; }
		public string CONTA_PROV_CONTRIB_DEB { get; set; }
		public string AUXILIAR_PROV_CONTRIB_DEB { get; set; }
		public string HISTORICO_PROV_CONTRIB_DEB { get; set; }
		public string CCUSTO_PROV_CONTRIB_DEB { get; set; }
		public string IND_AUTO_PATROC { get; set; }
		public string CONTRIB_PATROC { get; set; }
		public string ADIANT_REFERENCIA { get; set; }
		public string COMP_SAL_AUX_DOENCA { get; set; }
		public string SAL_UTILIZADO { get; set; }
		public decimal? VL_BENEF_MIN { get; set; }
		public string COMPARA_BENEF_MIN { get; set; }
		public decimal? COEF_BASE_TS_MASC { get; set; }
		public decimal? COEF_POR_ANO_TS_MASC { get; set; }
		public decimal? COEF_MAXIMO_TS_MASC { get; set; }
		public decimal? COEF_BASE_TS_FEM { get; set; }
		public decimal? COEF_POR_ANO_TS_FEM { get; set; }
		public decimal? COEF_MAXIMO_TS_FEM { get; set; }
		public decimal? COEF_BASE_ID_MASC { get; set; }
		public decimal? COEF_POR_ANO_ID_MASC { get; set; }
		public decimal? COEF_MAXIMO_ID_MASC { get; set; }
		public decimal? COEF_BASE_ID_FEM { get; set; }
		public decimal? COEF_POR_ANO_ID_FEM { get; set; }
		public decimal? COEF_MAXIMO_ID_FEM { get; set; }
		public string CONTRIB_JOIA { get; set; }
		public string FORM_SALMIN { get; set; }
		public decimal? PERC_MAX_RESGATE { get; set; }
		public string FCALC_FUND_SUPL_COMP { get; set; }
		public string FCALC_FUND_SUPL_TRANSF { get; set; }
		public string ACEITA_TRANSF_PECULIO { get; set; }
		public string ACEITA_TRANSF_INVALIDEZ { get; set; }
		public decimal? IDADE_PERD_CARENCIA { get; set; }
		public string RETIRA_TMP_CONTRIB { get; set; }
		public string RETIRA_TMP_EMP { get; set; }
		public string RETIRA_TMP_FUND { get; set; }
		public string FCAL_TSC_FUND { get; set; }
		public string FCAL_TSC_NFUND { get; set; }
		public decimal? QTD_MAX_TSC { get; set; }
		public string FCAL_TSCP_FUND { get; set; }
		public string FCAL_TSCP_NFUND { get; set; }
		public decimal? QTD_MAX_TSCP { get; set; }
		public string DIA_BASE_REF { get; set; }
		public decimal? QTD_DIAS_CALC { get; set; }
		public decimal? TABELA_ATUARIAL { get; set; }
		public decimal? LIM_NUM_PAG { get; set; }
		public string MOEDA_BENEF_MIN { get; set; }
		public decimal? NUM_SAL_PREV_HIP { get; set; }
		public string MOEDA_PBC_PREV_HIP { get; set; }
		public string MOEDA_COR_PREV_HIP { get; set; }
		public string MOEDA_LIM_PREV_HIP { get; set; }
		public string INI_PAG_REQ_AFAST { get; set; }
		public decimal? TOLERANCIA_REV { get; set; }
		public string CD_SIT_PLANO_DEST { get; set; }
		public string CD_SIT_EMP_DEST { get; set; }
		public string FCALC_RESERVA_MAT { get; set; }
		public string TIPO_CALC_TSC { get; set; }
		public string TIPO_CALC_TSCP { get; set; }
		public string FCAL_MIN_PGU_COP { get; set; }
		public string FCAL_MIN_PGU_SOP { get; set; }
		public string FCAL_MAX_PGU_COP { get; set; }
		public string FCAL_MAX_PGU_SOP { get; set; }
		public string COTA_RP_FD { get; set; }
		public string CD_TIPO_CONTRIB_PASSIVO { get; set; }
		public decimal? MAX_CONTR_MASC { get; set; }
		public decimal? MAX_CONTR_FEM { get; set; }
		public decimal? MAX_CONTR_FUND { get; set; }
		public decimal? TMP_MAX_IDADE_MASC { get; set; }
		public decimal? TMP_MAX_IDADE_FEM { get; set; }
		public decimal? TMP_MAX_IDADE_FUND { get; set; }
		public decimal? TMP_MAX_EMP_MASC { get; set; }
		public decimal? TMP_MAX_EMP_FEM { get; set; }
		public decimal? TMP_MAX_EMP_FUND { get; set; }
		public decimal? TMP_MAX_FUND_MASC { get; set; }
		public decimal? TMP_MAX_FUND_FEM { get; set; }
		public decimal? TMP_MAX_FUND_FUND { get; set; }
		public decimal? TSERV_PERD_CARENCIA { get; set; }
		public decimal? FUND_PERD_CARENCIA { get; set; }
		public string TSERV_RET_TMP_CONT { get; set; }
		public string TSERV_RET_TMP_IDADE { get; set; }
		public string TSERV_RET_TMP_FUND { get; set; }
		public string FUND_RET_TMP_CONT { get; set; }
		public string FUND_RET_TMP_IDADE { get; set; }
		public string FUND_RET_TMP_TSERV { get; set; }
		public string ORDEM_FATOR_REDUTOR { get; set; }
		public string UTILIZA_RENDAS_COMPL { get; set; }
		public string TIPO_REDUTOR_TS { get; set; }
		public string TIPO_REDUTOR_ID { get; set; }
		public string ORIGEM_TRANSF { get; set; }
		public string APLICA_M_ARIMETICA { get; set; }
		public decimal? ACRESC_TMP_CONTRIB { get; set; }
		public decimal? ACRESC_TMP_SERVIC { get; set; }
		public decimal? ACRESC_TMP_FUND { get; set; }
		public decimal? ACRESC_TMP_IDADE { get; set; }
		public string DISP_ARRENDONDAMENTO { get; set; }
		public decimal? TX_JUROS_ANUAL { get; set; }
		public int? IDADE_MAX_TABUA { get; set; }
		public int? IDADE_MAX_DEP_TEMP { get; set; }
		public decimal? REVERSAO_PENSAO { get; set; }
		public decimal? COTA_FAMILIAR { get; set; }
		public decimal? COTA_INDIVIDUAL { get; set; }
		public string FCALC_RVITAL_CREV { get; set; }
		public string FCALC_RVITAL_SREV { get; set; }
		public string FCALC_RVITAL_TMIN { get; set; }
		public string FCALC_RPRAZO_DETERM { get; set; }
		public string CONTA_PROV_CONTPAT_CRED { get; set; }
		public string CONTA_PROV_CONTPAT_DEB { get; set; }
		public string AUXILIAR_PROV_CONTPAT_CRED { get; set; }
		public string AUXILIAR_PROV_CONTPAT_DEB { get; set; }
		public string HISTORICO_PROV_CONTPAT_CRED { get; set; }
		public string HISTORICO_PROV_CONTPAT_DEB { get; set; }
		public string CCUSTO_PROV_CONTPAT_CRED { get; set; }
		public string CCUSTO_PROV_CONTPAT_DEB { get; set; }
		public string UTILIZA_DIB_PBC { get; set; }
		public decimal? LIM_NUM_PAG_INI { get; set; }
		public string UTILIZA_RUB_BMINIMO { get; set; }
		public string COMPARA_BENEF_CALC { get; set; }
		public string ABONO_INTEGRAL { get; set; }
		public string INI_PAG_REQ_AFAST_TRANSF { get; set; }
		public decimal? PRAZO_CALC_DIB_FUND_TRANSF { get; set; }
		public string TIPO_CALC_DIB_FUND_TRANSF { get; set; }
		public string CALC_PAG_ANTECIPACAO { get; set; }
		public string CD_SIT_PLANO_DEST_VESTING { get; set; }
		public string RES_MAT_INFORMADA { get; set; }
		public string RENDA_VINCULADA { get; set; }
		public string CD_ESPECIE_CARENCIA { get; set; }
		public string FCAL_MAX_BMIN { get; set; }
		public string FCALC_TRANSF_BMIN { get; set; }
		public string FCALC_TRANSF_BMAX { get; set; }
		public string FCALC_TRANSF_ASS_BMIN { get; set; }
		public string FCALC_TRANSF_ASS_BMAX { get; set; }
		public string INI_PAG_REQ_AFAST_2 { get; set; }
		public string TIPO_CALC_PRAZO_DIB { get; set; }
		public decimal? PRAZO_REQ_DIB_FUND { get; set; }
		public string CD_SIT_PLANO_DEST_TERM { get; set; }
		public string CD_SIT_PLANO_DEST_PAGUNICO { get; set; }
		public decimal? PRAZO_PAGTO_MIN { get; set; }
		public decimal? PRAZO_PAGTO_MAX { get; set; }
		public decimal? PRAZO_PAGTO_INT { get; set; }
		public string TRANSF_FORMULA_CD { get; set; }
		public string CALC_SEM_CORR_MONET { get; set; }
		public string OPCAO_RECB_13 { get; set; }
		public decimal? QTD_DIA_UTIL_COTA { get; set; }
		public string INF_DT_PAGTO_SAQUE { get; set; }
		public string ESTRUT_FORM_CALC_CD { get; set; }
		public string TIPO_COMP_LIMITANTE { get; set; }
		public string CD_MOTIVO_DESLIG_DEST_TERM { get; set; }
		public string CD_MOTIVO_DESLIG_DEST_PAGUNICO { get; set; }
		public string CD_SIT_PLANO_DEST_AP { get; set; }
		public decimal? FTIPO_CALC_CD { get; set; }
		public decimal? CAR_EXG_IDADE { get; set; }
		public decimal? CAR_EXG_CONTR { get; set; }
		public string FCALC_FUND_CA { get; set; }
		public string FCALC_FUND_FCA { get; set; }
		public string FCALC_FUND_FA { get; set; }
		public string FCALC_FUND_CBM { get; set; }
		public string UTILIZA_SAL_PBC { get; set; }
		public string CUSTEIO_PROVISAO_DEB { get; set; }
		public string CUSTEIO_PROVISAO_CRED { get; set; }
		public string CUSTEIO_PROV_CONTRIB_CRED { get; set; }
		public string CUSTEIO_PROV_CONTRIB_DEB { get; set; }
		public string CUSTEIO_PROV_CONTPAT_CRED { get; set; }
		public string CUSTEIO_PROV_CONTPAT_DEB { get; set; }
		public string UTILIZA_DT_FICHA { get; set; }
		public string CD_RUBRICA_DIFERENCA { get; set; }
		public decimal? PERC_MIN_RIND { get; set; }
		public decimal? PERC_MAX_RIND { get; set; }
		public string CD_TIPO_COB { get; set; }
		public string CK_ISENTA_IR { get; set; }
		public decimal? CAR_MIN_FUND_MASC { get; set; }
		public decimal? COEF_POR_ANO_TF_MASC { get; set; }
		public decimal? COEF_BASE_TF_MASC { get; set; }
		public decimal? COEF_MAXIMO_TF_MASC { get; set; }
		public decimal? CAR_MIN_FUND_FEM { get; set; }
		public decimal? COEF_POR_ANO_TF_FEM { get; set; }
		public decimal? COEF_BASE_TF_FEM { get; set; }
		public decimal? COEF_MAXIMO_TF_FEM { get; set; }
		public string UTILIZA_REAJ_DIF { get; set; }
		public string FCALC_TRANSF_COMP_PENSAO { get; set; }
		public string FCALC_TRANSF_ASS_PENSAO { get; set; }
		public string MOEDA_COR_PBC_FUND_ESPECIAL { get; set; }
		public DateTime? DT_MOEDA_COR_PBC_FUND_ESPECIAL { get; set; }
		public string CK_INDICE_ESPECIAL { get; set; }
		public decimal? PERC_PAGTO_MIN { get; set; }
		public decimal? PERC_PAGTO_MAX { get; set; }
		public string SEPARA_SALDO_RISCO { get; set; }
	}
}