/*Config
    RetornaLista
    Retorno
        -WebBloqueioFuncEntidade
*/

SELECT BL.*,
       FU.DES_FUNCIONALIDADE,
       EE.SIGLA_ENTID,
       PL.DS_PLANO       
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON BL.OID_FUNCIONALIDADE = FU.OID_FUNCIONALIDADE
    LEFT OUTER JOIN TB_PLANOS PL ON PL.CD_FUNDACAO = BL.CD_FUNDACAO AND PL.CD_PLANO = BL.CD_PLANO
    LEFT OUTER JOIN TB_EMPRESA EP ON EP.CD_FUNDACAO = BL.CD_FUNDACAO AND EP.CD_EMPRESA = BL.CD_EMPRESA
    LEFT OUTER JOIN EE_ENTIDADE EE ON EE.COD_ENTID = EP.COD_ENTID
WHERE DTA_FIM IS NULL
ORDER BY FU.DES_FUNCIONALIDADE, DTA_INICIO DESC