/*Config
    RetornaLista
    Retorno
        -WebBloqueioFuncEntidade
    Parametros
        -CD_FUNDACAO:string
		-NUM_FUNCIONALIDADE:decimal
		-CD_EMPRESA:string
		-NUM_MATRICULA:string
		-CD_PLANO:string
		-CD_PLANO2:string
		-CD_PLANO3:string
		-DTA_FIM:DateTime
*/

SELECT 1 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         = @CD_EMPRESA
  AND BL.CD_PLANO           in (@CD_PLANO, @CD_PLANO2, @CD_PLANO3) 
  AND BL.NUM_MATRICULA      = @NUM_MATRICULA
UNION ALL

SELECT 2 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         = @CD_EMPRESA
  AND BL.CD_PLANO           is null
  AND BL.NUM_MATRICULA      = @NUM_MATRICULA
UNION ALL

SELECT 3 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         is null
  AND BL.CD_PLANO           in (@CD_PLANO, @CD_PLANO2, @CD_PLANO3)
  AND BL.NUM_MATRICULA      = @NUM_MATRICULA
UNION ALL

SELECT 4 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         is null
  AND BL.CD_PLANO           is null
  AND BL.NUM_MATRICULA      = @NUM_MATRICULA
UNION ALL

SELECT 5 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         = @CD_EMPRESA
  AND BL.CD_PLANO           in (@CD_PLANO, @CD_PLANO2, @CD_PLANO3)
  AND BL.NUM_MATRICULA      IS NULL
UNION ALL

SELECT 6 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         = @CD_EMPRESA
  AND BL.CD_PLANO           IS NULL
  AND BL.NUM_MATRICULA      IS NULL
UNION ALL

SELECT 7 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         IS NULL
  AND BL.CD_PLANO           in (@CD_PLANO, @CD_PLANO2, @CD_PLANO3)
  AND BL.NUM_MATRICULA      IS NULL
UNION ALL

SELECT 8 AS NIVEL,
       BL.*
FROM WEB_BLOQUEIO_FUNC BL
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = BL.OID_FUNCIONALIDADE
WHERE BL.CD_FUNDACAO        = @CD_FUNDACAO
  AND FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (BL.DTA_FIM > @DTA_FIM OR BL.DTA_FIM IS NULL)
  AND BL.CD_EMPRESA         IS NULL
  AND BL.CD_PLANO           IS NULL
  AND BL.NUM_MATRICULA      IS NULL
ORDER BY NIVEL