/*==============================================================*/
/* carga WEB_FUNCIONALIDADE                                                                                 */
/*==============================================================*/
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (1, 'HOME ATIVOS E AUTOPATROCINADOS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (2, 'HOME ASISSTIDOS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (3, 'HOME PENSIONISTAS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (4, 'SEUS DADOS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (5, 'SEUS PLANOS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (6, 'EXTRATO', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (7, 'CONTRACHEQUE ASISSTIDOS / PENSIONISTAS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (8, 'INFORME DE RENDIMENTOS ASSISTIDOS / PENSIONISTAS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (9, 'DOCUMENTOS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (10, 'FALE CONOSCO (MENSAGENS)', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (11, 'FORMULÁRIOS', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (12, 'SIMULADOR DE BENEFÍCIOS CODEPREV', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (13, 'EMPRÉSTIMOS - CONSULTA', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (14, 'EMPRÉSTIMOS - SIMULAÇÃO', 'SIM', 'NAO');
INSERT INTO WEB_FUNCIONALIDADE (NUM_FUNCIONALIDADE, DES_FUNCIONALIDADE, IND_ATIVO, IND_USA_PROTOCOLO) VALUES (15, 'EMPRÉSTIMOS - CONTRATAÇÃO', 'SIM', 'NAO');