SELECT * FROM CS_FUNCIONARIO 
INNER JOIN CS_PLANOS_VINC ON CS_PLANOS_VINC.NUM_INSCRICAO = CS_FUNCIONARIO.NUM_INSCRICAO
WHERE CS_PLANOS_VINC.CD_PLANO = '0003'
  AND NUM_MATRICULA IN (SELECT NOM_LOGIN FROM WEB_USUARIO);