/*==============================================================*/
/* CRIAÇÃO DA TABELA: WEB_PERC_CONTRIBUICAO                     */
/*==============================================================*/
CREATE TABLE WEB_PERC_CONTRIBUICAO (
   OID_PERC_CONTRIBUICAO NUMERIC(10)          IDENTITY,
   CD_FUNDACAO          VARCHAR(2)           NOT NULL,
   CD_PLANO             VARCHAR(4)           NOT NULL,
   CD_TIPO_CONTRIBUICAO VARCHAR(2)           NOT NULL,
   VAL_PERC_CONTRIBUICAO NUMERIC(15,8)        NOT NULL,
   CONSTRAINT WEB_PERC_CONTRIBUICAO_PK PRIMARY KEY NONCLUSTERED (OID_PERC_CONTRIBUICAO)
)
go

CREATE UNIQUE INDEX WEB_PERC_CONTRIBUICAO_UK01 ON WEB_PERC_CONTRIBUICAO (
CD_FUNDACAO ASC,
CD_PLANO ASC,
CD_TIPO_CONTRIBUICAO ASC
)
go


/*==============================================================*/
/* CARGA DA TABELA: WEB_PERC_CONTRIBUICAO                       */
/* PARA A PREVIRB                                               */
/*==============================================================*/
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','07', 16);	--RENDA MENSAL
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','11', 16);  --RENDA MENSAL - PART
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','30',0.6);  --RISCO - PECÚLIO
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','33',0.6);  --RISCO - PECÚLIO - PART
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','32', 0.03); --RISCO - FUNERAL
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','35', 0.03); --RISCO - FUNERAL - PART
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','09', 1.505); --RISCO-PENSÃO-MORTE
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','15', 1.505); --RISCO - PENSÃO P/MORTE - PART
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','31', 0.655); --RISCO - INVALIDEZ
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','34', 0.655); --RISCO - INVALIDEZ - PART
INSERT INTO WEB_PERC_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, VAL_PERC_CONTRIBUICAO) VALUES ('01', '0002','54',0.212); --RISCO - AUXILIO DOENCA
