DROP VIEW VW_FUNC_PLANO_DADOS;
GO
CREATE VIEW VW_FUNC_PLANO_DADOS
AS 
(
SELECT EE_ENTIDADE.NOME_ENTID      
      ,EE_ENTIDADE.COD_ENTID
      ,EE_ENTIDADE.NUM_AGENCIA
      ,EE_ENTIDADE.NUM_CONTA
      ,EE_ENTIDADE.NUM_BANCO
      ,EE_ENTIDADE.CPF_CGC
   
      ,CS_FUNCIONARIO.CK_INADIPLENTE
      ,CS_FUNCIONARIO.CD_FUNDACAO
      ,CS_FUNCIONARIO.CD_EMPRESA
	  ,CS_FUNCIONARIO.NUM_MATRICULA
	  ,CS_FUNCIONARIO.NUM_INSCRICAO
	  ,CS_FUNCIONARIO.DT_ADMISSAO
	  ,CS_FUNCIONARIO.CD_SIT_EMPRESA 
	  ,CS_FUNCIONARIO.DT_VINCULO_FUNDACAO
	  ,CS_FUNCIONARIO.DT_RECADASTRO
   
	  ,CS_DADOS_PESSOAIS.DT_NASCIMENTO
	  ,CS_DADOS_PESSOAIS.SEXO
	  ,CS_DADOS_PESSOAIS.EMAIL_AUX
	  ,CS_DADOS_PESSOAIS.FONE_CELULAR
	  ,CS_PLANOS_VINC.CD_PLANO
	  ,CS_PLANOS_VINC.DT_INSC_PLANO
	  ,CS_PLANOS_VINC.CD_SIT_PLANO
	  ,TB_SIT_PLANO.CD_CATEGORIA
	   
  FROM CS_FUNCIONARIO
 INNER JOIN CS_DADOS_PESSOAIS 
         ON CS_DADOS_PESSOAIS.COD_ENTID = CS_FUNCIONARIO.COD_ENTID 
 INNER JOIN CS_PLANOS_VINC 
         ON CS_PLANOS_VINC.NUM_INSCRICAO = CS_FUNCIONARIO.NUM_INSCRICAO
 INNER JOIN TB_SIT_PLANO 
         ON TB_SIT_PLANO.CD_SIT_PLANO = CS_PLANOS_VINC.CD_SIT_PLANO
 INNER JOIN EE_ENTIDADE 
         ON EE_ENTIDADE.COD_ENTID = CS_FUNCIONARIO.COD_ENTID

 );