DROP TABLE WEB_ADESAO_EMPRESA_PLANO;

/*==============================================================*/
/* Table: WEB_ADESAO_EMPRESA_PLANO                              */
/*==============================================================*/
CREATE TABLE WEB_ADESAO_EMPRESA_PLANO (
   OID_ADESAO_EMPRESA_PLANO NUMERIC(10)          IDENTITY,
   CD_FUNDACAO          VARCHAR(2)             NOT NULL,
   CD_EMPRESA           VARCHAR(4)             NOT NULL,
   CD_PLANO             VARCHAR(4)             NOT NULL,
   CONSTRAINT PK_WEB_ADESAO_EMPRESA_PLANO_PK PRIMARY KEY (OID_ADESAO_EMPRESA_PLANO)
)
go

/*==============================================================*/
/* Index: WEB_ADESAO_EMPRESA_PLANO_UK01                         */
/*==============================================================*/
CREATE UNIQUE INDEX WEB_ADESAO_EMPRESA_PLANO_UK01 ON WEB_ADESAO_EMPRESA_PLANO (
CD_FUNDACAO ASC,
CD_EMPRESA ASC,
CD_PLANO ASC
)
go

INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0001',	'0002');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0001',	'0003');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0001',	'0005');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0001',	'0099');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0002',	'0002');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0002',	'0003');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0002',	'0005');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0002',	'0099');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0003',	'0003');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0003',	'0005');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0004',	'0003');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0004',	'0005');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0005',	'0004');
INSERT INTO WEB_ADESAO_EMPRESA_PLANO (CD_FUNDACAO, CD_EMPRESA, CD_PLANO) VALUES ('01', '0006',	'0005');