ALTER TABLE WEB_CALENDARIO_PGT ADD CD_PLANO VARCHAR(4) NULL;

UPDATE WEB_CALENDARIO_PGT SET CD_PLANO = '0001';

INSERT INTO WEB_CALENDARIO_PGT
(DES_MES, NUM_DIA, CD_PLANO) 
(
	SELECT DES_MES, NUM_DIA, '0002'
	FROM WEB_CALENDARIO_PGT
	WHERE CD_PLANO = '0001'
);

INSERT INTO WEB_CALENDARIO_PGT
(DES_MES, NUM_DIA, CD_PLANO) 
(
	SELECT DES_MES, NUM_DIA, '0003'
	FROM WEB_CALENDARIO_PGT
	WHERE CD_PLANO = '0001'
);

UPDATE WEB_CALENDARIO_PGT 
SET NUM_DIA = 27
WHERE CD_PLANO = '0002'
  AND DES_MES IN( 'Dezembro', 'Abono Anual');