--DECLARE @MATRICULA varchar(9) = '035857861';

DISABLE TRIGGER LOG_CS_DADOS_PESSOAIS_DEL ON CS_DADOS_PESSOAIS;
DISABLE TRIGGER LOG_CS_DADOS_PESSOAIS_INS ON CS_DADOS_PESSOAIS;
DISABLE TRIGGER LOG_CS_DADOS_PESSOAIS_UPD ON CS_DADOS_PESSOAIS;

UPDATE CS_DADOS_PESSOAIS 
SET EMAIL_AUX = 'roniely@intech.com.br', 
	FONE_CELULAR = '61999999349' 
--WHERE COD_ENTID IN (SELECT COD_ENTID FROM CS_FUNCIONARIO WHERE NUM_MATRICULA = @MATRICULA);

SELECT DISTINCT EMAIL_AUX, FONE_CELULAR
FROM CS_DADOS_PESSOAIS
--WHERE COD_ENTID IN (SELECT COD_ENTID FROM CS_FUNCIONARIO WHERE NUM_MATRICULA = @MATRICULA);