--DECLARE @MATRICULA varchar(9) = '035857861';

UPDATE CS_DADOS_PESSOAIS 
SET EMAIL_AUX = 'roniely@intech.com.br', 
	FONE_CELULAR = '061999999349' 
--WHERE COD_ENTID IN (SELECT COD_ENTID FROM CS_FUNCIONARIO WHERE NUM_MATRICULA = @MATRICULA);

SELECT EMAIL_AUX, FONE_CELULAR
FROM CS_DADOS_PESSOAIS
--WHERE COD_ENTID IN (SELECT COD_ENTID FROM CS_FUNCIONARIO WHERE NUM_MATRICULA = @MATRICULA);