DROP VIEW VW_FUNC_PLANO_DADOS;
GO
CREATE VIEW VW_FUNC_PLANO_DADOS
AS 
(
SELECT CS_FUNCIONARIO.CD_FUNDACAO
	  ,CS_FUNCIONARIO.NUM_INSCRICAO
      ,CS_FUNCIONARIO.CD_EMPRESA
	  ,CS_FUNCIONARIO.NUM_MATRICULA
      ,EE_ENTIDADE.NOME_ENTID      
      ,EE_ENTIDADE.COD_ENTID
      ,EE_ENTIDADE.CPF_CGC
	  ,CS_PLANOS_VINC.CD_PLANO
	  ,TB_PLANOS.DS_PLANO
	  ,TB_CATEGORIA.DS_CATEGORIA
	  ,CS_PLANOS_VINC.CD_SIT_PLANO
	  , 'N' AS PENSIONISTA	   
  FROM CS_FUNCIONARIO
 INNER JOIN CS_DADOS_PESSOAIS 
         ON CS_DADOS_PESSOAIS.COD_ENTID = CS_FUNCIONARIO.COD_ENTID 
 INNER JOIN CS_PLANOS_VINC 
         ON CS_PLANOS_VINC.NUM_INSCRICAO = CS_FUNCIONARIO.NUM_INSCRICAO
 INNER JOIN TB_PLANOS 
		 ON TB_PLANOS.CD_FUNDACAO = CS_PLANOS_VINC.CD_FUNDACAO AND
		   TB_PLANOS.CD_PLANO = CS_PLANOS_VINC.CD_PLANO	
 INNER JOIN TB_SIT_PLANO 
         ON TB_SIT_PLANO.CD_SIT_PLANO = CS_PLANOS_VINC.CD_SIT_PLANO
 INNER JOIN TB_CATEGORIA
		 ON TB_CATEGORIA.CD_CATEGORIA = TB_SIT_PLANO.CD_CATEGORIA
 INNER JOIN EE_ENTIDADE 
         ON EE_ENTIDADE.COD_ENTID = CS_FUNCIONARIO.COD_ENTID

 UNION ALL
 
 SELECT GB_RECEBEDOR_BENEFICIO.CD_FUNDACAO
	  ,GB_RECEBEDOR_BENEFICIO.NUM_INSCRICAO
      ,GB_RECEBEDOR_BENEFICIO.CD_EMPRESA
	  ,GB_RECEBEDOR_BENEFICIO.NUM_MATRICULA
      ,EE_ENTIDADE.NOME_ENTID      
      ,EE_ENTIDADE.COD_ENTID
      ,EE_ENTIDADE.CPF_CGC
	  ,CS_PLANOS_VINC.CD_PLANO
	  ,TB_PLANOS.DS_PLANO
	  ,CS_PLANOS_VINC.CD_SIT_PLANO
	  ,'PENSIONISTA' AS DS_CATEGORIA	   
	  , 'S' AS PENSIONISTA
  FROM GB_RECEBEDOR_BENEFICIO
 INNER JOIN CS_FUNCIONARIO
		 ON CS_FUNCIONARIO.CD_FUNDACAO = GB_RECEBEDOR_BENEFICIO.CD_FUNDACAO AND
		    CS_FUNCIONARIO.NUM_INSCRICAO = GB_RECEBEDOR_BENEFICIO.NUM_INSCRICAO
 INNER JOIN CS_DADOS_PESSOAIS 
         ON CS_DADOS_PESSOAIS.COD_ENTID = GB_RECEBEDOR_BENEFICIO.COD_ENTID 
 INNER JOIN CS_PLANOS_VINC 
         ON CS_PLANOS_VINC.CD_FUNDACAO = CS_FUNCIONARIO.CD_FUNDACAO AND
		    CS_PLANOS_VINC.NUM_INSCRICAO = CS_FUNCIONARIO.NUM_INSCRICAO
 INNER JOIN TB_PLANOS 
		 ON TB_PLANOS.CD_FUNDACAO = CS_PLANOS_VINC.CD_FUNDACAO AND
		   TB_PLANOS.CD_PLANO = CS_PLANOS_VINC.CD_PLANO	
 INNER JOIN EE_ENTIDADE 
         ON EE_ENTIDADE.COD_ENTID = GB_RECEBEDOR_BENEFICIO.COD_ENTID 
WHERE GB_RECEBEDOR_BENEFICIO.CD_TIPO_RECEBEDOR = 'G'
 );