IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('WEB_BLOQUEIO_FUNC')
            AND   TYPE = 'U')
   DROP TABLE WEB_BLOQUEIO_FUNC
go

CREATE TABLE [dbo].[WEB_BLOQUEIO_FUNC](
       [OID_BLOQUEIO_FUNC] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
       [CD_FUNDACAO] [varchar](2) NOT NULL,
       [CD_EMPRESA] [varchar](4) NULL,
       [CD_PLANO] [varchar](4) NULL,
       [OID_FUNCIONALIDADE] [numeric](10, 0) NOT NULL,
       [DTA_INICIO] [datetime] NULL,
       [DTA_FIM] [datetime] NULL,
       [DTA_CRIACAO] [datetime] NOT NULL,
       [TXT_MOTIVO_BLOQUEIO] [varchar](4000) NULL,
       [NOM_USUARIO] [varchar](100) NOT NULL,
       [IND_ATIVO] [varchar](3) NOT NULL,
       [NUM_MATRICULA] [varchar](9) NULL,
CONSTRAINT [WEB_BLOQUEIO_FUNC_PK] PRIMARY KEY CLUSTERED 
(
       [OID_BLOQUEIO_FUNC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WEB_BLOQUEIO_FUNC] ADD  DEFAULT ('SIM') FOR [IND_ATIVO]
GO

ALTER TABLE [dbo].[WEB_BLOQUEIO_FUNC]  WITH CHECK ADD  CONSTRAINT [WEB_BLOQUEIO_FUNC_FK01] FOREIGN KEY([OID_FUNCIONALIDADE])
REFERENCES [dbo].[WEB_FUNCIONALIDADE] ([OID_FUNCIONALIDADE])
GO

ALTER TABLE [dbo].[WEB_BLOQUEIO_FUNC] CHECK CONSTRAINT [WEB_BLOQUEIO_FUNC_FK01]
GO
