CREATE TABLE [dbo].[WEB_FATOR_RISCO](
	[OID_FATOR_RISCO] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[CD_FUNDACAO] [varchar](2) NOT NULL,
	[CD_PLANO] [varchar](4) NOT NULL,
	[NUM_FAIXA_INI] [numeric](10, 0) NOT NULL,
	[NUM_FAIXA_FIM] [numeric](10, 0) NOT NULL,
	[VAL_FATOR_INVALIDEZ] [numeric](30, 20) NOT NULL,
	[VAL_FATOR_MORTE] [numeric](30, 20) NOT NULL,
 CONSTRAINT [WEB_FATOR_RISCO_PK] PRIMARY KEY CLUSTERED 
(
	[OID_FATOR_RISCO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


