CREATE TABLE [dbo].[WEB_MENSAGEM](
	[OID_MENSAGEM] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[TXT_TITULO] [varchar](100) NOT NULL,
	[TXT_CORPO] [varchar](4000) NOT NULL,
	[DTA_MENSAGEM] [datetime] NOT NULL,
	[DTA_EXPIRACAO] [datetime] NULL,
	[CD_FUNDACAO] [varchar](2) NOT NULL,
	[CD_EMPRESA] [varchar](4) NULL,
	[CD_PLANO] [varchar](4) NULL,
	[CD_SIT_PLANO] [varchar](2) NULL,
	[COD_ENTID] [numeric](10, 0) NULL,
	[IND_MOBILE] [varchar](3) NOT NULL,
	[IND_PORTAL] [varchar](3) NOT NULL,
	[IND_EMAIL] [varchar](3) NOT NULL,
	[IND_SMS] [varchar](3) NOT NULL,
 CONSTRAINT [WEB_MENSAGEM_PK] PRIMARY KEY CLUSTERED 
(
	[OID_MENSAGEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WEB_MENSAGEM]  WITH CHECK ADD  CONSTRAINT [CKC_IND_EMAIL_WEB_MENS] CHECK  ((([IND_EMAIL]='NAO' OR [IND_EMAIL]='SIM') AND [IND_EMAIL]=upper([IND_EMAIL])))
GO

ALTER TABLE [dbo].[WEB_MENSAGEM] CHECK CONSTRAINT [CKC_IND_EMAIL_WEB_MENS]
GO

ALTER TABLE [dbo].[WEB_MENSAGEM]  WITH CHECK ADD  CONSTRAINT [CKC_IND_MOBILE_WEB_MENS] CHECK  ((([IND_MOBILE]='NAO' OR [IND_MOBILE]='SIM') AND [IND_MOBILE]=upper([IND_MOBILE])))
GO

ALTER TABLE [dbo].[WEB_MENSAGEM] CHECK CONSTRAINT [CKC_IND_MOBILE_WEB_MENS]
GO

ALTER TABLE [dbo].[WEB_MENSAGEM]  WITH CHECK ADD  CONSTRAINT [CKC_IND_PORTAL_WEB_MENS] CHECK  ((([IND_PORTAL]='NAO' OR [IND_PORTAL]='SIM') AND [IND_PORTAL]=upper([IND_PORTAL])))
GO

ALTER TABLE [dbo].[WEB_MENSAGEM] CHECK CONSTRAINT [CKC_IND_PORTAL_WEB_MENS]
GO

ALTER TABLE [dbo].[WEB_MENSAGEM]  WITH CHECK ADD  CONSTRAINT [CKC_IND_SMS_WEB_MENS] CHECK  ((([IND_SMS]='NAO' OR [IND_SMS]='SIM') AND [IND_SMS]=upper([IND_SMS])))
GO

ALTER TABLE [dbo].[WEB_MENSAGEM] CHECK CONSTRAINT [CKC_IND_SMS_WEB_MENS]
GO

