CREATE TABLE WEB_USUARIO(
	OID_USUARIO number(10, 0) NOT NULL,
	NOM_LOGIN varchar2(60) NOT NULL,
	PWD_USUARIO varchar2(200) NOT NULL,
	IND_BLOQUEADO varchar2(1) NOT NULL,
	NUM_TENTATIVA number(5, 0) NOT NULL,
	DES_LOTACAO varchar2(20) NULL,
	IND_ADMINISTRADOR varchar2(1) NOT NULL,
	IND_ATIVO varchar2(1) NOT NULL,
	NOM_USUARIO_CRIACAO varchar2(60) NULL,
	DTA_CRIACAO date NULL,
	NOM_USUARIO_ATUALIZACAO varchar2(60) NULL,
	DTA_ATUALIZACAO date NULL,
	CD_EMPRESA varchar2(4) NOT NULL,
	SEQ_RECEBEDOR number(10, 0) NULL,
	IND_PRIMEIRO_ACESSO varchar2(1) NOT NULL);
    
ALTER TABLE WEB_USUARIO
ADD CONSTRAINT PK_WEB_USUARIO PRIMARY KEY (OID_USUARIO);

CREATE SEQUENCE S_WEB_USUARIO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20;
