CREATE TABLE WEB_LGPD_CONSENTIMENTO(
	OID_LGPD_CONSENTIMENTO NUMBER(10, 0) NOT NULL,
	COD_IDENTIFICADOR varchar2(25) NOT NULL,
	CD_FUNDACAO varchar2(2) NOT NULL,
	COD_CPF varchar2(11) NOT NULL,
	DTA_CONSENTIMENTO date NOT NULL,
	TXT_IPV4 varchar2(15) NULL,
	TXT_IPV6 varchar2(50) NULL,
	TXT_DISPOSITIVO varchar2(100) NULL,
	TXT_ORIGEM varchar2(100) NOT NULL);
	
ALTER TABLE WEB_LGPD_CONSENTIMENTO
ADD CONSTRAINT PK_WEB_LGPD_CONSENTIMENTO PRIMARY KEY (OID_LGPD_CONSENTIMENTO);

CREATE SEQUENCE S_WEB_LGPD_CONSENTIMENTO
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20;