CREATE TABLE [dbo].[WEB_CALENDARIO_PGT](
	[OID_CALENDARIO_PGT] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[DES_MES] [varchar](50) NOT NULL,
	[NUM_DIA] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_WEB_CALENDARIO_PGT] PRIMARY KEY CLUSTERED 
(
	[OID_CALENDARIO_PGT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

INSERT INTO WEB_CALENDARIO_PGT VALUES('Janeiro', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Fevereiro', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Março', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Abril', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Maio', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Junho', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Julho', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Agosto', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Setembro', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Outubro', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Novembro', 1);
INSERT INTO WEB_CALENDARIO_PGT VALUES('Dezembro', 1);