CREATE TABLE [dbo].[WEB_RELACIONAMENTO](
	[OID_RELACIONAMENTO] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[CD_FUNDACAO] [varchar](2) NOT NULL,
	[COD_CPF] [varchar](11) NOT NULL,
	[DTA_ENVIO] [datetime] NOT NULL,
	[TXT_EMAIL_DESTINATARIO] [varchar](300) NOT NULL,
	[TXT_EMAIL_REMETENTE] [varchar](100) NOT NULL,
	[OID_ASSUNTO] [numeric](10, 0) NOT NULL,
	[TXT_MENSAGEM] [varchar](4000) NOT NULL,
	[TXT_IPV4] [varchar](15) NULL,
	[TXT_IPV6] [varchar](50) NULL,
	[TXT_DISPOSITIVO] [varchar](100) NULL,
 CONSTRAINT [WEB_RELACIONAMENTO_PK] PRIMARY KEY CLUSTERED 
(
	[OID_RELACIONAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[WEB_RELACIONAMENTO]  WITH CHECK ADD  CONSTRAINT [WEB_RELACIONAMENTO_FK01] FOREIGN KEY([OID_ASSUNTO])
REFERENCES [dbo].[WEB_ASSUNTO] ([OID_ASSUNTO]);

ALTER TABLE [dbo].[WEB_RELACIONAMENTO] CHECK CONSTRAINT [WEB_RELACIONAMENTO_FK01];

