CREATE TABLE [dbo].[WEB_AREA_FUNDACAO](
	[OID_AREA_FUNDACAO] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[CD_FUNDACAO] [varchar](2) NOT NULL,
	[DES_AREA_FUNDACAO] [varchar](100) NOT NULL,
	[TXT_EMAIL] [varchar](300) NOT NULL,
	[IND_ATIVO] [varchar](3) NOT NULL,
 CONSTRAINT [WEB_AREA_FUNDACAO_PK] PRIMARY KEY CLUSTERED 
(
	[OID_AREA_FUNDACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[WEB_AREA_FUNDACAO]  WITH CHECK ADD  CONSTRAINT [CKC_IND_ATIVO_WEB_AREA] CHECK  ((([IND_ATIVO]='NAO' OR [IND_ATIVO]='SIM') AND [IND_ATIVO]=upper([IND_ATIVO])))
ALTER TABLE [dbo].[WEB_AREA_FUNDACAO] CHECK CONSTRAINT [CKC_IND_ATIVO_WEB_AREA]



CREATE TABLE [dbo].[WEB_ASSUNTO](
	[OID_ASSUNTO] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[OID_AREA_FUNDACAO] [numeric](10, 0) NOT NULL,
	[CD_FUNDACAO] [varchar](2) NOT NULL,
	[TXT_ASSUNTO] [varchar](200) NOT NULL,
	[IND_ATIVO] [varchar](3) NOT NULL,
 CONSTRAINT [WEB_ASSUNTO_PK] PRIMARY KEY CLUSTERED 
(
	[OID_ASSUNTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[WEB_ASSUNTO]  WITH CHECK ADD  CONSTRAINT [WEB_ASSUNTO_FK01] FOREIGN KEY([OID_AREA_FUNDACAO])
REFERENCES [dbo].[WEB_AREA_FUNDACAO] ([OID_AREA_FUNDACAO])

ALTER TABLE [dbo].[WEB_ASSUNTO] CHECK CONSTRAINT [WEB_ASSUNTO_FK01]
ALTER TABLE [dbo].[WEB_ASSUNTO]  WITH CHECK ADD  CONSTRAINT [CKC_IND_ATIVO_WEB_ASSU] CHECK  ((([IND_ATIVO]='NAO' OR [IND_ATIVO]='SIM') AND [IND_ATIVO]=upper([IND_ATIVO])))
ALTER TABLE [dbo].[WEB_ASSUNTO] CHECK CONSTRAINT [CKC_IND_ATIVO_WEB_ASSU]
