IF EXISTS (SELECT 1
            FROM  SYSOBJECTS
           WHERE  ID = OBJECT_ID('WEB_CONTRIBUICAO')
            AND   TYPE = 'U')
   DROP TABLE WEB_CONTRIBUICAO
go

/*==============================================================*/
/* Table: WEB_CONTRIBUICAO                                      */
/*==============================================================*/
CREATE TABLE WEB_CONTRIBUICAO (
   OID_CONTRIBUICAO     NUMERIC(10)          IDENTITY,
   CD_FUNDACAO          VARCHAR(2)           NOT NULL,
   CD_PLANO             VARCHAR(4)           NULL,
   CD_TIPO_CONTRIBUICAO VARCHAR(2)           NULL,
   COD_GRUPO_CONTRIBUICAO VARCHAR(10)          NULL,
   CONSTRAINT PK_WEB_CONTRIBUICAO PRIMARY KEY (OID_CONTRIBUICAO)
)
go

INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0002', '68', 'BASPART'); --CONTRIB NORMAL PART 0002 743
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0002', '69', 'BASPATRO'); --CONTRIB NORMAL PATROC 0002 743
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0002', '75', 'BASPART13'); --CONTRIB NORMAL PART 0002 - 13 742
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0002', '76', 'BASPATRO13'); --CONTRIB NORMAL PATR 0002 - 13 741
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0002', '79', 'BASPART'); --CONT AUTO NORMAL PART CD02 7
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0002', 'C4', 'BASPATRO'); --CONT AUTO NORMAL PATRO CD-02 7
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '03', 'BASPART'); --INDIVIDUAL - 0003 3842
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '04', 'BASPATRO'); --PATRONAL - 0003 3846
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '25', 'BASPART'); --INDIVIDUAL AUTO-PATROC - 03 93
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '35', 'BASPART13'); --CONTRIB NORMAL 13 SAL - 0001 2
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '36', 'BASPART13'); --INDIVIDUAL 13 SAL - 0003 3832
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '37', 'BASPATRO13'); --PATRONAL 13 SAL - 0003 3828
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '60', 'BASPATRO13'); --CONTR. PATRONAL 13 SAL - 0001 2
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0003', '76', 'BASPATRO13'); --CONTRIB NORMAL PATR 0002 - 13 1
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'M1', 'BASPART'); --PESSOAL NORMAL 831
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'M2', 'BASPART13'); --PESSOAL 13 ║ 831
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'M3', 'FACPART'); --PESSOAL FACULTATIVA 246
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'M4', 'FACPART13'); --PESSOAL FACULTATIVA 13 ║ 247
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'M5', 'BASPATRO'); --PATRONAL NORMAL 831
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'M6', 'BASPATRO13'); --PATRONAL 13 830
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'N1', 'BASPART'); --PESSOAL NORMAL AUTO CD 04 1
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0004', 'N5', 'BASPART'); --PATRONAL NORMAL AUTO CD 04 1
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0005', 'P1', 'BASPART'); --PESSOAL NORMAL CD 05 207
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0005', 'P2', 'BASPART13'); --PESSOAL 13 CD 05 207
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0005', 'P5', 'BASPATRO'); --PATRONAL NORMAL CD 05 207
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0005', 'P6', 'BASPATRO13'); --PATRONAL 13 CD 05 207
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0005', 'P8', 'BASPART'); --AUTO PESSOAL NORMAL CD 05 3
INSERT INTO WEB_CONTRIBUICAO (CD_FUNDACAO, CD_PLANO, CD_TIPO_CONTRIBUICAO, COD_GRUPO_CONTRIBUICAO) VALUES ('01',
'0005', 'Q1', 'BASPATRO'); --AUTO PATRONAL NORMAL CD 05 3
