/*Config
    Retorno
        -FundacaoEntidade
    Parametros
        -CD_FUNDACAO:string
*/

SELECT TB_FUNDACAO.*,
    EE_ENTIDADE.NOME_ENTID,
    EE_ENTIDADE.END_ENTID,
    EE_ENTIDADE.BAIRRO_ENTID,
    EE_ENTIDADE.CEP_ENTID,
    EE_ENTIDADE.UF_ENTID,
    EE_ENTIDADE.FONE_ENTID,
    EE_ENTIDADE.FAX_ENTID,
    EE_ENTIDADE.CPF_CGC
FROM TB_FUNDACAO
INNER JOIN EE_ENTIDADE ON EE_ENTIDADE.COD_ENTID = TB_FUNDACAO.COD_ENTID
WHERE CD_FUNDACAO = @CD_FUNDACAO