/*Config
    RetornaLista
    Retorno
        -CadastroRubricasEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_EMPRESA:string
        -ANO_MES_INICIO:string
        -ANO_MES_FIM:string
*/

SELECT DISTINCT CC_CADASTRO_RUBRICAS.*,
    TB_RUBRICA.DS_RUBRICA
FROM CC_CADASTRO_RUBRICAS
INNER JOIN TB_RUBRICA ON CC_CADASTRO_RUBRICAS.CD_RUBRICA = TB_RUBRICA.CD_RUBRICA
  AND CC_CADASTRO_RUBRICAS.CD_EMPRESA = TB_RUBRICA.CD_EMPRESA
WHERE  ( CC_CADASTRO_RUBRICAS.CD_FUNDACAO = @CD_FUNDACAO )
       AND ( CC_CADASTRO_RUBRICAS.NUM_INSCRICAO = @NUM_INSCRICAO )
       AND ( CC_CADASTRO_RUBRICAS.CD_EMPRESA = @CD_EMPRESA )
       AND ( '' + CC_CADASTRO_RUBRICAS.ANO_COMPETENCIA + CC_CADASTRO_RUBRICAS.MES_COMPETENCIA BETWEEN @ANO_MES_INICIO AND @ANO_MES_FIM )
       AND ( CC_CADASTRO_RUBRICAS.MES_COMPETENCIA <> '13' )
       AND ( TB_RUBRICA.CONCESSAO_BENEF = 'S' ) 