/*Config
    RetornaLista
    Retorno
        -CadastroRubricasEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -CD_EMPRESA:string
        -ANO_REF:string
        -MES_REF:string
        -CD_RUBRICA:string
*/

SELECT 
    CC_CADASTRO_RUBRICAS.*,
    TB_RUBRICA.DS_RUBRICA,
    TB_RUBRICA.DEBITO_CREDITO 
FROM CC_CADASTRO_RUBRICAS 
INNER JOIN TB_RUBRICA ON CC_CADASTRO_RUBRICAS.CD_FUNDACAO = TB_RUBRICA.CD_FUNDACAO 
  AND TB_RUBRICA.CD_EMPRESA = CC_CADASTRO_RUBRICAS.CD_EMPRESA 
  AND TB_RUBRICA.CD_RUBRICA = CC_CADASTRO_RUBRICAS.CD_RUBRICA 
WHERE (CC_CADASTRO_RUBRICAS.CD_FUNDACAO = @CD_FUNDACAO) 
AND (CC_CADASTRO_RUBRICAS.CD_EMPRESA = @CD_EMPRESA) 
AND (CC_CADASTRO_RUBRICAS.NUM_INSCRICAO = @NUM_INSCRICAO) 
AND (CC_CADASTRO_RUBRICAS.ANO_REF = @ANO_REF) 
AND (CC_CADASTRO_RUBRICAS.MES_REF = @MES_REF) 
AND (CC_CADASTRO_RUBRICAS.CD_RUBRICA = @CD_RUBRICA)