/*Config
    Retorno
        -void
    Parametros
        -CD_SITUACAO:string
        -CD_MOTIVO_QUIT:string
        -DT_QUITACAO:DateTime
        -DT_REF_QUITACAO:DateTime
        -VL_PRINC_QUITACAO:decimal
        -VL_JUROS_QUITACAO:decimal
        -VL_PREST_ATRASO:decimal
        -VL_CORR_PREST_ATRASO:decimal
        -VL_PRINC_PREST_ATRASO:decimal
        -VL_JUROS_PREST_ATRASO:decimal
        -VL_JUROS_MORA_PREST:decimal
        -VL_MULTA_PREST:decimal
        -VL_JUROS_PREST_MES:decimal
        -VL_PRINC_PREST_MES:decimal
        -VL_CORRECAO_SALDO_QUITACAO:decimal
        -VL_DESCONTO_QUITACAO:decimal
        -VL_TX_INAD_QUITACAO:decimal
        -VL_TX_ADM_QUITACAO:decimal
        -VL_TX_SEGURO_QUITACAO:decimal
        -VL_ACRESCIMO_QUITACAO:decimal
        -VL_SEGURO_QUIT:decimal
        -VL_TX_ADM_MES_QUIT:decimal
        -VL_SEGURO_PRORATA:decimal
        -VL_ADM_PRORATA:decimal
        -VL_CORR_JUROS_PREST_MES:decimal
        -VL_CORR_PRINC_PREST_MES:decimal
        -VL_IOF_COMPL_QUIT:decimal
		-CD_FUNDACAO:string
		-ANO_CONTRATO:decimal
		-NUM_CONTRATO:decimal
*/

UPDATE CE_CONTRATOS
SET    CD_SITUACAO = @CD_SITUACAO,
       CD_MOTIVO_QUIT = @CD_MOTIVO_QUIT,
       DT_QUITACAO = @DT_QUITACAO,
       DT_REF_QUITACAO = @DT_REF_QUITACAO,
       VL_PRINC_QUITACAO = @VL_PRINC_QUITACAO,
       VL_JUROS_QUITACAO = @VL_JUROS_QUITACAO,
       VL_PREST_ATRASO = @VL_PREST_ATRASO,
       VL_CORR_PREST_ATRASO = @VL_CORR_PREST_ATRASO,
       VL_PRINC_PREST_ATRASO = @VL_PRINC_PREST_ATRASO,
       VL_JUROS_PREST_ATRASO = @VL_JUROS_PREST_ATRASO,
       VL_JUROS_MORA_PREST = @VL_JUROS_MORA_PREST,
       VL_MULTA_PREST = @VL_MULTA_PREST,
       VL_JUROS_PREST_MES = @VL_JUROS_PREST_MES,
       VL_PRINC_PREST_MES = @VL_PRINC_PREST_MES,
       VL_CORRECAO_SALDO_QUITACAO = @VL_CORRECAO_SALDO_QUITACAO,
       VL_DESCONTO_QUITACAO = @VL_DESCONTO_QUITACAO,
       VL_TX_INAD_QUITACAO = @VL_TX_INAD_QUITACAO,
       VL_TX_ADM_QUITACAO = @VL_TX_ADM_QUITACAO,
       VL_TX_SEGURO_QUITACAO = @VL_TX_SEGURO_QUITACAO,
       VL_ACRESCIMO_QUITACAO = @VL_ACRESCIMO_QUITACAO,
       VL_SEGURO_QUIT = @VL_SEGURO_QUIT,
       VL_TX_ADM_MES_QUIT = @VL_TX_ADM_MES_QUIT,
       VL_SEGURO_PRORATA = @VL_SEGURO_PRORATA,
       VL_ADM_PRORATA = @VL_ADM_PRORATA,
       VL_CORR_JUROS_PREST_MES = @VL_CORR_JUROS_PREST_MES,
       VL_CORR_PRINC_PREST_MES = @VL_CORR_PRINC_PREST_MES,
       VL_IOF_COMPL_QUIT = @VL_IOF_COMPL_QUIT
WHERE  ( CD_FUNDACAO = @CD_FUNDACAO )
       AND ( ANO_CONTRATO = @ANO_CONTRATO )
       AND ( NUM_CONTRATO = @NUM_CONTRATO ) 