/*Config
    Retorno
        -dynamic
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -ANO_CONTRATO:string
        -NUM_CONTRATO:string
        -NUM_SEQ_GR_FAMIL:string
*/

SELECT EE.NOME_ENTID AS NOME_PARTICIPANTE,
       EE.CPF_CGC AS CPF_PARTICIPANTE,
       EE2.NOME_ENTID AS NOME_PENSIONISTA,
       EE2.CPF_CGC AS CPF_PENSIONISTA,
       ST.DS_SITUACAO,
       PL.DS_PLANO,
       NA.DS_NATUR,
       MO.DS_MODAL,
       CE.*
FROM CE_CONTRATOS CE
    INNER JOIN CE_MODALIDADE MO ON MO.CD_MODAL = CE.CD_MODAL
    INNER JOIN CE_NATUREZA NA ON NA.CD_NATUR = CE.CD_NATUR
    INNER JOIN CE_SITUACAO_CONTRATO ST ON ST.CD_SITUACAO = CE.CD_SITUACAO
    INNER JOIN CS_FUNCIONARIO FN ON FN.CD_FUNDACAO = CE.CD_FUNDACAO
        AND FN.NUM_INSCRICAO = CE.NUM_INSCRICAO
    INNER JOIN EE_ENTIDADE EE ON EE.COD_ENTID = FN.COD_ENTID
    INNER JOIN TB_PLANOS PL ON PL.CD_FUNDACAO = CE.CD_FUNDACAO
        AND PL.CD_PLANO = CE.CD_PLANO
    LEFT OUTER JOIN GB_RECEBEDOR_BENEFICIO RB ON RB.CD_FUNDACAO = CE.CD_FUNDACAO 
        AND RB.NUM_INSCRICAO = CE.NUM_INSCRICAO
        AND RB.NUM_SEQ_GR_FAMIL = CE.NUM_SEQ_GR_FAMIL
    LEFT OUTER JOIN EE_ENTIDADE EE2 ON EE2.COD_ENTID = RB.COD_ENTID
WHERE CE.CD_FUNDACAO = @CD_FUNDACAO
  AND CE.NUM_INSCRICAO = @NUM_INSCRICAO
  AND CE.ANO_CONTRATO = @ANO_CONTRATO
  AND CE.NUM_CONTRATO = @NUM_CONTRATO
  AND CE.NUM_SEQ_GR_FAMIL = @NUM_SEQ_GR_FAMIL