/*Config
    Retorno
        -HistRendasEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -CD_PLANO:string
        -ANO_PROCESSO:string
        -NUM_PROCESSO:decimal
        -CD_ESPECIE:string
*/

SELECT * 
FROM GB_HIST_RENDAS HR1
WHERE CD_FUNDACAO = @CD_FUNDACAO
  AND CD_EMPRESA = @CD_EMPRESA
  AND CD_PLANO = @CD_PLANO
  AND ANO_PROCESSO = @ANO_PROCESSO
  AND NUM_PROCESSO = @NUM_PROCESSO
  AND CD_ESPECIE = @CD_ESPECIE
  AND DT_INIC_VALIDADE = (SELECT MAX(DT_INIC_VALIDADE)
						  FROM GB_HIST_RENDAS
						    WHERE CD_FUNDACAO = HR1.CD_FUNDACAO
						  	  AND CD_EMPRESA = HR1.CD_EMPRESA
						  	  AND CD_PLANO = HR1.CD_PLANO
						  	  AND ANO_PROCESSO = HR1.ANO_PROCESSO
						  	  AND NUM_PROCESSO = HR1.NUM_PROCESSO
						  	  AND CD_ESPECIE = HR1.CD_ESPECIE)