/*Config
    Retorno
        -RecebedorBeneficioEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -NUM_INSCRICAO:string
        -SEQ_RECEBEDOR:string
*/

SELECT RB.*
FROM GB_RECEBEDOR_BENEFICIO RB
    INNER JOIN GB_PROCESSOS_BENEFICIO PB ON PB.CD_FUNDACAO = RB.CD_FUNDACAO
        AND PB.NUM_INSCRICAO = RB.NUM_INSCRICAO
    INNER JOIN GB_ESPECIE_BENEFICIO EB ON EB.CD_ESPECIE = PB.CD_ESPECIE
WHERE PB.DT_TERMINO >= GETDATE()
  AND RB.CD_FUNDACAO = @CD_FUNDACAO
  AND RB.CD_EMPRESA = @CD_EMPRESA
  AND RB.NUM_INSCRICAO = @NUM_INSCRICAO
  AND RB.SEQ_RECEBEDOR = @SEQ_RECEBEDOR