/*Config
    Retorno
        -ProtocoloEntidade
    Parametros
        -OID_PROTOCOLO:decimal
*/

SELECT WEB_PROTOCOLO.*,
    WEB_FUNCIONALIDADE.DES_FUNCIONALIDADE,
    EE_ENTIDADE.NOME_ENTID,
    TB_PLANOS.DS_PLANO
FROM   WEB_PROTOCOLO 
INNER JOIN WEB_FUNCIONALIDADE ON WEB_FUNCIONALIDADE.OID_FUNCIONALIDADE = WEB_PROTOCOLO.OID_FUNCIONALIDADE 
INNER JOIN CS_FUNCIONARIO ON CS_FUNCIONARIO.NUM_MATRICULA = WEB_PROTOCOLO.NUM_MATRICULA
INNER JOIN EE_ENTIDADE ON EE_ENTIDADE.COD_ENTID = CS_FUNCIONARIO.COD_ENTID
LEFT OUTER JOIN TB_PLANOS ON TB_PLANOS.CD_PLANO = WEB_PROTOCOLO.CD_PLANO
WHERE ( WEB_PROTOCOLO.OID_PROTOCOLO = @OID_PROTOCOLO)
ORDER  BY WEB_PROTOCOLO.DTA_SOLICITACAO DESC