/*Config
    Retorno
        -ProtocoloEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -CD_PLANO:string
        -NUM_MATRICULA:string
        -NUM_FUNCIONALIDADE:decimal
*/

SELECT WEB_PROTOCOLO.CD_EMPRESA, 
       WEB_PROTOCOLO.CD_FUNDACAO, 
       WEB_PROTOCOLO.CD_PLANO, 
       WEB_PROTOCOLO.COD_IDENTIFICADOR, 
       WEB_PROTOCOLO.DTA_EFETIVACAO, 
       WEB_PROTOCOLO.DTA_SOLICITACAO, 
       WEB_PROTOCOLO.NUM_MATRICULA, 
       WEB_PROTOCOLO.OID_FUNCIONALIDADE, 
       WEB_PROTOCOLO.OID_PROTOCOLO, 
       WEB_PROTOCOLO.SEQ_RECEBEDOR, 
       WEB_PROTOCOLO.TXT_DISPOSITIVO, 
       WEB_PROTOCOLO.TXT_IPV4, 
       WEB_PROTOCOLO.TXT_IPV4_EXTERNO, 
       WEB_PROTOCOLO.TXT_IPV6, 
       WEB_PROTOCOLO.TXT_MOTIVO_RECUSA, 
       WEB_PROTOCOLO.TXT_ORIGEM, 
       WEB_PROTOCOLO.TXT_TRANSACAO, 
       WEB_PROTOCOLO.TXT_TRANSACAO2, 
       WEB_PROTOCOLO.TXT_USUARIO_EFETIVACAO, 
       WEB_PROTOCOLO.TXT_USUARIO_SOLICITACAO 
FROM   WEB_PROTOCOLO 
INNER JOIN WEB_FUNCIONALIDADE 
    ON WEB_FUNCIONALIDADE.OID_FUNCIONALIDADE = WEB_PROTOCOLO.OID_FUNCIONALIDADE 
WHERE ( WEB_PROTOCOLO.CD_FUNDACAO = @CD_FUNDACAO ) 
  AND ( WEB_PROTOCOLO.CD_EMPRESA = @CD_EMPRESA ) 
  AND ( WEB_PROTOCOLO.CD_PLANO = @CD_PLANO ) 
  AND ( WEB_PROTOCOLO.NUM_MATRICULA = @NUM_MATRICULA ) 
  AND ( WEB_PROTOCOLO.DTA_EFETIVACAO IS NULL ) 
  AND ( WEB_PROTOCOLO.TXT_MOTIVO_RECUSA IS NULL ) 
  AND ( WEB_FUNCIONALIDADE.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE ) 
ORDER  BY WEB_PROTOCOLO.DTA_SOLICITACAO DESC 