/*Config
    Retorno
        -RegraNaturezaEntidade
    Parametros
        -QUANTIDADE:int
*/

SELECT *
FROM CE_REGRA_NATUREZA
WHERE QTD_REFORMAS = @QUANTIDADE
  AND DT_INI_VIGENCIA = (SELECT MAX(DT_INI_VIGENCIA) FROM CE_REGRA_NATUREZA WHERE QTD_REFORMAS = @QUANTIDADE)
ORDER BY DT_INI_VIGENCIA DESC