/*Config
	RetornaLista
	Retorno
		-CSAvaliacaoEntidade
*/

SELECT AVA.ANO_REF,
       AVA.MES_REF,
       FUN.NUM_MATRICULA,
	   AVA.CD_EMPRESA,
	   AVA.CD_PLANO,
	   CONVERT (VARCHAR, AVA.DT_NASCIMENTO, 103) as DT_NASCIMENTO,
	   CONVERT (VARCHAR, AVA.DT_ADMISSAO, 103) as DT_ADMISSAO,
	   CONVERT (VARCHAR, AVA.DT_INSCRICAO, 103) as DT_INSCRICAO,
	   CONVERT (VARCHAR, AVA.DT_APOSENTADORIA , 103) as DT_APOSENTADORIA,
	   AVA.SEXO,
	   AVA.SRC,
	   ISNULL(AVA.FUNDO_INDIVIDUAL,0) + ISNULL(AVA.FUNDO_INDIV_PORTADO,0) AS FUNDO_INDIVIDUAL,
	   ISNULL(AVA.FUNDO_PATROCINADO,0)  AS FUNDO_PATROCINADO,
	   AVA.VLR_CONTRIB_PART as VLR_CONTRIB_PART,
	   AVA.VLR_CONTRIB_EMP VLR_CONTRIB_EMP	   
FROM CS_AVALIACAO AVA
	INNER JOIN CS_FUNCIONARIO FUN 
		ON FUN.CD_FUNDACAO = AVA.CD_FUNDACAO AND
		   FUN.NUM_INSCRICAO = AVA.NUM_INSCRICAO	
	INNER JOIN CS_PLANOS_VINC PV 
		ON PV.CD_FUNDACAO = AVA.CD_FUNDACAO AND
		   PV.NUM_INSCRICAO = AVA.NUM_INSCRICAO AND
		   PV.CD_PLANO = AVA.CD_PLANO
	INNER JOIN TB_SIT_PLANO SP 
	    ON SP.CD_SIT_PLANO = PV.CD_SIT_PLANO
WHERE AVA.CD_PLANO IN ('0003', '0005', '0004')
	AND SP.CD_CATEGORIA = '1'
	AND AVA.ANO_REF = (SELECT MAX(AVA2.ANO_REF) 
						FROM CS_AVALIACAO AVA2 
							INNER JOIN CS_FUNCIONARIO FUN2  ON FUN2.CD_FUNDACAO = AVA.CD_FUNDACAO 
								AND FUN2.NUM_INSCRICAO = AVA2.NUM_INSCRICAO	
							INNER JOIN CS_PLANOS_VINC PV2 ON PV2.CD_FUNDACAO = AVA2.CD_FUNDACAO 
								AND PV2.NUM_INSCRICAO = AVA2.NUM_INSCRICAO 
								AND PV2.CD_PLANO = AVA2.CD_PLANO
							INNER JOIN TB_SIT_PLANO SP2 ON SP2.CD_SIT_PLANO = PV2.CD_SIT_PLANO
							WHERE AVA2.CD_PLANO IN ('0003', '0005', '0004') 
							AND SP2.CD_CATEGORIA = '1')

		AND AVA.MES_REF = (SELECT MAX(AVA2.MES_REF) 
						FROM CS_AVALIACAO AVA2 
						INNER JOIN CS_FUNCIONARIO FUN2  ON FUN2.CD_FUNDACAO = AVA.CD_FUNDACAO 
								AND FUN2.NUM_INSCRICAO = AVA2.NUM_INSCRICAO	
							INNER JOIN CS_PLANOS_VINC PV2 ON PV2.CD_FUNDACAO = AVA2.CD_FUNDACAO 
								AND PV2.NUM_INSCRICAO = AVA2.NUM_INSCRICAO 
								AND PV2.CD_PLANO = AVA2.CD_PLANO
							INNER JOIN TB_SIT_PLANO SP2 ON SP2.CD_SIT_PLANO = PV2.CD_SIT_PLANO
							WHERE AVA2.CD_PLANO IN ('0003', '0005', '0004') 
							AND SP2.CD_CATEGORIA = '1' 
							AND AVA2.ANO_REF = AVA.ANO_REF)