/*Config
    RetornaLista
    Retorno
        -DocumentoEntidade
    Parametros
        -CD_PLANO:string
        -OID_DOCUMENTO_PASTA:decimal?
*/

SELECT WEB_DOCUMENTO.*
FROM WEB_DOCUMENTO
WHERE OID_DOCUMENTO NOT IN (SELECT OID_DOCUMENTO FROM  WEB_DOCUMENTO_PLANO WHERE CD_PLANO <> @CD_PLANO)
  AND ((OID_DOCUMENTO_PASTA = @OID_DOCUMENTO_PASTA)
   OR (@OID_DOCUMENTO_PASTA IS NULL AND OID_DOCUMENTO_PASTA IS NULL))