/*Config
    RetornaLista
    Retorno
        -DocumentoEntidade
    Parametros
        -OID_DOCUMENTO_PASTA:decimal?
*/

SELECT *
 FROM WEB_DOCUMENTO D LEFT JOIN WEB_DOCUMENTO_PLANO DP
 ON D.OID_DOCUMENTO = DP.OID_DOCUMENTO
 LEFT JOIN TB_PLANOS P
 ON DP.CD_PLANO = P.CD_PLANO
 WHERE (OID_DOCUMENTO_PASTA = @OID_DOCUMENTO_PASTA)
   OR (@OID_DOCUMENTO_PASTA IS NULL AND OID_DOCUMENTO_PASTA IS NULL)