/*Config
    RetornaLista
    Retorno
        -DocumentoEntidade
    Parametros
        -OID_DOCUMENTO_PASTA:decimal?
		-CD_PLANO:string
		-ORDER_CRITERIA:string
*/

SELECT *
 FROM WEB_DOCUMENTO D LEFT JOIN WEB_DOCUMENTO_PLANO DP
 ON D.OID_DOCUMENTO = DP.OID_DOCUMENTO
 LEFT JOIN TB_PLANOS P
 ON DP.CD_PLANO = P.CD_PLANO
 WHERE ((OID_DOCUMENTO_PASTA = @OID_DOCUMENTO_PASTA)
   OR (@OID_DOCUMENTO_PASTA IS NULL AND OID_DOCUMENTO_PASTA IS NULL))
   AND ((P.CD_PLANO = @CD_PLANO  OR DP.CD_PLANO IS NULL)
   OR (@CD_PLANO IS NULL AND P.CD_PLANO IS NULL))
   ORDER BY 
CASE
   WHEN @ORDER_CRITERIA = 'nome' THEN D.TXT_TITULO
END,
CASE
	WHEN @ORDER_CRITERIA = 'data' THEN D.DTA_INCLUSAO
END