/*Config
    RetornaLista
    Retorno
        -FichaFechamentoPrevesEntidade
    Parametros
        -CD_FUNDACAO:string
        -CD_EMPRESA:string
        -CD_PLANO:string
        -NUM_INSCRICAO:string
*/

SELECT FF.*,
	LO.DS_LOTACAO
FROM CC_FICHA_FECHAMENTO_PREVES FF
INNER JOIN CS_FUNCIONARIO FUNC ON FUNC.NUM_INSCRICAO = FF.NUM_INSCRICAO
INNER JOIN TB_LOTACAO LO ON LO.CD_LOTACAO = FUNC.CD_LOTACAO
						AND LO.CD_EMPRESA = FUNC.CD_EMPRESA
WHERE FF.CD_FUNDACAO = @CD_FUNDACAO
  AND FF.CD_EMPRESA = @CD_EMPRESA
  AND FF.CD_PLANO = @CD_PLANO
  AND FF.NUM_INSCRICAO = @NUM_INSCRICAO
  AND FF.IND_ANALITICO_SINTETICO = 'S'
ORDER BY FF.ANO_REF,
         FF.ANO_COMP