/*Config
    RetornaLista
    Retorno
        -WebDocExigidoEntidade
    Parametros
        -NUM_FUNCIONALIDADE:int
        -CD_PLANO:string
		-IND_ATIVO:string
*/

SELECT DE.* 
FROM WEB_DOC_EXIGIDO DE
    INNER JOIN WEB_FUNCIONALIDADE FU ON FU.OID_FUNCIONALIDADE = DE.OID_FUNCIONALIDADE
WHERE FU.NUM_FUNCIONALIDADE = @NUM_FUNCIONALIDADE
  AND (DE.CD_PLANO IS NULL OR DE.CD_PLANO = @CD_PLANO)
  AND DE.IND_ATIVO = @IND_ATIVO