/*Config
    RetornaLista
    Retorno
        -DocumentoPastaEntidade
    Parametros
        -NOM_LOGIN:string
		-OID_DOCUMENTO_PASTA_PAI:decimal?
		-ORDER_CRITERIA:string
*/

SELECT WDP.OID_DOCUMENTO_PASTA, WDP.OID_DOCUMENTO_PASTA_PAI, WDP.NOM_PASTA, WDP.OID_GRUPO_USUARIO, WDP.DTA_INCLUSAO
FROM WEB_DOCUMENTO_PASTA WDP
 LEFT JOIN WEB_USUARIO_GRUPO WUG ON WDP.OID_GRUPO_USUARIO = WUG.OID_GRUPO_USUARIO
 LEFT JOIN WEB_USUARIO U ON U.OID_USUARIO = WUG.OID_USUARIO
WHERE (NOM_LOGIN = @NOM_LOGIN OR NOM_LOGIN IS NULL)
AND ((OID_DOCUMENTO_PASTA_PAI = @OID_DOCUMENTO_PASTA_PAI)
 OR (@OID_DOCUMENTO_PASTA_PAI IS NULL AND OID_DOCUMENTO_PASTA_PAI IS NULL))