/*Config
    RetornaLista
    Retorno
        -DocumentoPastaEntidade
    Parametros
        -OID_DOCUMENTO_PASTA_PAI:decimal?
*/

SELECT WDP.*, WGU.*, WDP2.NOM_PASTA AS 'NOM_PASTA_PAI'
 FROM WEB_DOCUMENTO_PASTA WDP LEFT JOIN WEB_GRUPO_USUARIO WGU
 ON WDP.OID_GRUPO_USUARIO = WGU.OID_GRUPO_USUARIO
  JOIN WEB_DOCUMENTO_PASTA WDP2
  ON WDP2.OID_DOCUMENTO_PASTA = WDP.OID_DOCUMENTO_PASTA_PAI