/*Config
    RetornaLista
    Retorno
        -PlanoVinculadoEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
*/

SELECT PV.NUM_INSCRICAO,
       PV.CD_PLANO,
       SP.CD_CATEGORIA,
       CT.DS_CATEGORIA,
       PV.CD_SIT_PLANO,
       SP.DS_SIT_PLANO,
	   CASE
		   WHEN SP.CD_CATEGORIA = '1' AND SP.CD_SIT_PLANO = '29' THEN 'SALDADO_EXTRAORD'
		   WHEN SP.CD_CATEGORIA = '4' AND SP.CD_SIT_PLANO = '20' THEN 'ASSISTIDO_ESPECIAL'
		   WHEN SP.CD_CATEGORIA = '4' AND SP.CD_SIT_PLANO IN ('22', '40', '42', '58') THEN 'PENSIONISTA'
	       WHEN SP.CD_CATEGORIA = '4' THEN 'ASSISTIDO'
		   ELSE 'ATIVO'
	   END AS 'GRUPO_RECADASTRAMENTO'
FROM CS_PLANOS_VINC PV 
    INNER JOIN TB_SIT_PLANO SP ON SP.CD_SIT_PLANO = PV.CD_SIT_PLANO
    INNER JOIN TB_CATEGORIA CT ON CT.CD_CATEGORIA = SP.CD_CATEGORIA
WHERE PV.CD_FUNDACAO = @CD_FUNDACAO
  AND PV.NUM_INSCRICAO = @NUM_INSCRICAO
ORDER BY SP.CD_CATEGORIA, SP.DS_SIT_PLANO