/*Config
    Retorno
        -void
    Parametros
        -COD_ENTID:int
        -CD_NACIONALIDADE:string
        -CD_GRAU_INSTRUCAO:string
        -CD_ESTADO_CIVIL:string
        -SEXO:string
        -NATURALIDADE:string
        -UF_NATURALIDADE:string
        -DT_NASCIMENTO:DateTime
        -NU_IDENT:string
        -ORG_EMIS_IDENT:string
        -DT_EMIS_IDENT:DateTime?
        -UF_EMIS_IDENT:string
        -NU_CTPS:string
        -SERIE_CTPS:string
        -UF_EMIS_CTPS:string
        -COD_BANCO_COB:string
        -COD_AGENC_COB:string
        -CD_TIPO_COB:string
        -NUM_CONTA_COB:string
        -NOME_PAI:string
        -NOME_MAE:string
        -NOME_CONJUGE:string
        -CPF_CONJUGE:string
        -EMAIL_AUX:string
        -FONE_CELULAR:string
*/

UPDATE CS_DADOS_PESSOAIS
SET CD_NACIONALIDADE =@CD_NACIONALIDADE, CD_GRAU_INSTRUCAO = @CD_GRAU_INSTRUCAO, CD_ESTADO_CIVIL = @CD_ESTADO_CIVIL, SEXO = @SEXO, NATURALIDADE = @NATURALIDADE, 
UF_NATURALIDADE = @UF_NATURALIDADE, DT_NASCIMENTO = @DT_NASCIMENTO, NU_IDENT = @NU_IDENT, ORG_EMIS_IDENT = @ORG_EMIS_IDENT, DT_EMIS_IDENT = @DT_EMIS_IDENT,
UF_EMIS_IDENT = @UF_EMIS_IDENT, NU_CTPS = @NU_CTPS, SERIE_CTPS = @SERIE_CTPS, UF_EMIS_CTPS = @UF_EMIS_CTPS, COD_BANCO_COB = @COD_BANCO_COB, 
COD_AGENC_COB = @COD_AGENC_COB, CD_TIPO_COB = @CD_TIPO_COB, NUM_CONTA_COB = @NUM_CONTA_COB, NOME_PAI = @NOME_PAI,
NOME_MAE = @NOME_MAE, NOME_CONJUGE = @NOME_CONJUGE, CPF_CONJUGE = @CPF_CONJUGE, EMAIL_AUX = @EMAIL_AUX, FONE_CELULAR = @FONE_CELULAR
WHERE COD_ENTID = @COD_ENTID
