/*Config
    Retorno
        -DadosPessoaisEntidade
    Parametros
        -COD_ENTID:string
*/

SELECT
    CS_DADOS_PESSOAIS.*,
    EE_ENTIDADE.CPF_CGC
FROM CS_DADOS_PESSOAIS
INNER JOIN EE_ENTIDADE ON EE_ENTIDADE.COD_ENTID = CS_DADOS_PESSOAIS.COD_ENTID
WHERE CS_DADOS_PESSOAIS.COD_ENTID = @COD_ENTID