/*Config
    Retorno
        -EmpresaEntidade
    Parametros
        -CD_EMPRESA:string
*/

SELECT TB_EMPRESA.*,
    EE_ENTIDADE.NOME_ENTID,
	EE_ENTIDADE.SIGLA_ENTID,
    EE_ENTIDADE.CPF_CGC
FROM TB_EMPRESA
INNER JOIN EE_ENTIDADE ON EE_ENTIDADE.COD_ENTID = TB_EMPRESA.COD_ENTID
WHERE TB_EMPRESA.CD_EMPRESA = @CD_EMPRESA