/*Config
    RetornaLista
    Retorno
        -EmpresaEntidade
	Parametros
		-CD_FUNDACAO:string
*/

SELECT TB_EMPRESA.*,
    EE_ENTIDADE.NOME_ENTID
FROM TB_EMPRESA
INNER JOIN EE_ENTIDADE ON EE_ENTIDADE.COD_ENTID = TB_EMPRESA.COD_ENTID
WHERE TB_EMPRESA.CD_FUNDACAO = @CD_FUNDACAO