/*Config
    RetornaLista
    Retorno
        -UsuarioGrupoEntidade
    Parametros
        -@OID_GRUPO_USUARIO:decimal
*/

SELECT DISTINCT
  FPD.CPF_CGC, FPD.NOME_ENTID
FROM   VW_FUNC_PLANO_DADOS FPD
JOIN WEB_USUARIO U ON FPD.CPF_CGC = U.NOM_LOGIN
JOIN WEB_USUARIO_GRUPO UG ON UG.OID_USUARIO = U.OID_USUARIO
WHERE UG.OID_GRUPO_USUARIO = @OID_GRUPO_USUARIO