/*Config
    RetornaLista
    Retorno
        -PrestacaoEntidade
    Parametros
        -CD_FUNDACAO:string
        -NUM_INSCRICAO:string
        -DT_INCIAL:DateTime
        -DT_FINAL:DateTime
*/

SELECT CE_PRESTACOES.*
FROM CE_PRESTACOES
INNER JOIN CE_CONTRATOS ON CE_CONTRATOS.NUM_CONTRATO = CE_PRESTACOES.NUM_CONTRATO
AND CE_CONTRATOS.ANO_CONTRATO = CE_PRESTACOES.ANO_CONTRATO
WHERE (CE_CONTRATOS.NUM_INSCRICAO = @NUM_INSCRICAO)
  AND (CE_PRESTACOES.DT_VENC >= @DT_INCIAL)
  AND (CE_PRESTACOES.DT_VENC <= @DT_FINAL)
  AND (CE_CONTRATOS.CD_FUNDACAO = @CD_FUNDACAO)
  AND (CE_PRESTACOES.DT_PAGTO IS NOT NULL)