/*Config
	Retorno
        -bool
    Parametros
		-OID_RECAD_PUBLICO_ALVO: decimal
        -IND_SITUACAO_RECAD: string
        -NOM_USUARIO_ACAO: string
*/

UPDATE WEB_RECAD_PUBLICO_ALVO
	SET IND_SITUACAO_RECAD = @IND_SITUACAO_RECAD, NOM_USUARIO_ACAO = @NOM_USUARIO_ACAO
	WHERE OID_RECAD_PUBLICO_ALVO = @OID_RECAD_PUBLICO_ALVO