/*Config
    RetornaLista
    Retorno
        -WebRecadPublicoAlvoEntidade
    Parametros
        -CPF:string
		-DATA_ATUAL:DateTime
*/

SELECT PA.*,
	CA.DTA_TERMINO,
	CASE
		   WHEN SP.CD_CATEGORIA = '1' AND SP.CD_SIT_PLANO = '29' THEN 'SALDADO_EXTRAORD'
		   WHEN SP.CD_CATEGORIA = '4' AND SP.CD_SIT_PLANO = '20' THEN 'ASSISTIDO_ESPECIAL'
		   WHEN SP.CD_CATEGORIA = '4' AND SP.CD_SIT_PLANO IN ('22', '40', '42', '58') THEN 'PENSIONISTA'
	       WHEN SP.CD_CATEGORIA = '4' THEN 'ASSISTIDO'
		   ELSE 'ATIVO'
	   END AS 'GRUPO_RECADASTRAMENTO',
	   CASE
		   WHEN SP.CD_CATEGORIA = '1' AND SP.CD_SIT_PLANO = '29' THEN 4
		   WHEN SP.CD_CATEGORIA = '4' AND SP.CD_SIT_PLANO = '20' THEN 3
		   WHEN SP.CD_CATEGORIA = '4' AND SP.CD_SIT_PLANO IN ('22', '40', '42', '58') THEN 2
	       WHEN SP.CD_CATEGORIA = '4' THEN 1
		   ELSE 5
	   END AS 'CD_GRUPO_RECADASTRAMENTO'
  FROM WEB_RECAD_PUBLICO_ALVO PA
    INNER JOIN CS_FUNCIONARIO FN ON FN.CD_FUNDACAO = PA.CD_FUNDACAO
		AND FN.NUM_INSCRICAO = PA.NUM_INSCRICAO
    INNER JOIN EE_ENTIDADE EE ON EE.COD_ENTID = FN.COD_ENTID
    INNER JOIN WEB_RECAD_CAMPANHA CA ON CA.OID_RECAD_CAMPANHA = PA.OID_RECAD_CAMPANHA
	INNER JOIN CS_PLANOS_VINC PV ON PV.CD_FUNDACAO = PA.CD_FUNDACAO
	  AND PV.NUM_INSCRICAO = PA.NUM_INSCRICAO
	INNER JOIN TB_SIT_PLANO SP ON SP.CD_SIT_PLANO = PV.CD_SIT_PLANO
WHERE EE.CPF_CGC = @CPF
  AND CA.DTA_INICIO <= @DATA_ATUAL
  AND CA.DTA_TERMINO >= @DATA_ATUAL
  AND CA.IND_ATIVO = 'SIM'
  ORDER BY DTA_INICIO, CD_GRUPO_RECADASTRAMENTO DESC