/*Config
    RetornaLista
    Retorno
        -WebRecadParticipanteDadosEntidade
    Parametros
        -CD_FUNDACAO:string
		-NUM_INSCRICAO:string
*/

SELECT FN.CD_FUNDACAO,
       0 AS SEQ_RECEBEDOR,
       FN.NUM_INSCRICAO, 
       FN.CD_EMPRESA, 
       EE_EMP.SIGLA_ENTID AS NOM_EMPRESA,
       FN.NUM_MATRICULA, 
       EE.NOME_ENTID,
       DP.DT_NASCIMENTO,
       EE.CPF_CGC,
       DP.NU_IDENT,
       DP.ORG_EMIS_IDENT,
       DP.DT_EMIS_IDENT,
       DP.NATURALIDADE,
       DP.UF_NATURALIDADE,
       DP.NOME_MAE,
       DP.NOME_PAI,
       DP.CD_ESTADO_CIVIL,
       DP.NOME_CONJUGE,
       DP.CPF_CONJUGE,
       EE.CEP_ENTID,
       EE.END_ENTID,
       EE.NR_END_ENTID,
       EE.COMP_END_ENTID,
       EE.BAIRRO_ENTID,
       EE.CID_ENTID,
       EE.UF_ENTID,       
       DP.CD_PAIS,
       DP.EMAIL_AUX,
       DP.FONE_CELULAR,
       EE.FONE_ENTID,
       EE.NUM_BANCO,
       EE.NUM_AGENCIA,
       EE.NUM_CONTA,
       EE.POLIT_EXP       
  FROM CS_FUNCIONARIO FN 
    INNER JOIN EE_ENTIDADE EE ON EE.COD_ENTID = FN.COD_ENTID
    INNER JOIN CS_DADOS_PESSOAIS DP ON DP.COD_ENTID = FN.COD_ENTID
    INNER JOIN TB_EMPRESA EP ON EP.CD_FUNDACAO = FN.CD_FUNDACAO AND EP.CD_EMPRESA = FN.CD_EMPRESA
    INNER JOIN EE_ENTIDADE EE_EMP ON EE_EMP.COD_ENTID = EP.COD_ENTID
WHERE FN.CD_FUNDACAO = @CD_FUNDACAO
  AND FN.NUM_INSCRICAO = @NUM_INSCRICAO